using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Orbyss.ProgramKit.GeneratedSourceContract.Operations.Generation;

/// <summary>
/// Emits a byte-stable same-assembly compiler participation receipt only when
/// an exact nonce requests current-invocation evidence. Gate mechanics bind
/// freshness outside compiled outputs; the generator grants no authority and
/// performs no discovery.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GeneratedSourceContractReceiptGenerator :
    IIncrementalGenerator
{
    private const string NonceProperty =
        "build_property.ProgramKitPublicAnalyzerReceiptNonce";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        var nonce = context.AnalyzerConfigOptionsProvider.Select(
            static (options, _) =>
                options.GlobalOptions.TryGetValue(
                    NonceProperty,
                    out var value)
                    ? value
                    : string.Empty);
        context.RegisterSourceOutput(
            nonce,
            static (output, value) =>
            {
                if (!IsLowerHexNonce(value))
                {
                    return;
                }

                var source = string.Concat(
                    "// <auto-generated program-kit>",
                    "\n",
                    "// public-analyzer-receipt:generated-source-contract",
                    "\n");
                output.AddSource(
                    "ProgramKitGenerated/PublicAnalyzerReceipt/" +
                    "GeneratedSourceContractReceipt.cs",
                    SourceText.From(source, Encoding.UTF8));
            });
    }

    private static bool IsLowerHexNonce(string value) =>
        value.Length == 32 &&
        value.All(static character =>
            character is (>= '0' and <= '9') or
                (>= 'a' and <= 'f'));
}
