using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Orbyss.ProgramKit.GeneratedSourceContract.Operations.Generation;

/// <summary>
/// Emits a same-assembly compiler participation receipt for an exact nonce.
/// Gate mechanics validate and bind the emitted receipt; the generator grants
/// no authority and performs no discovery.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GeneratedSourceContractReceiptGenerator :
    IIncrementalGenerator
{
    private const string NonceProperty =
        "build_property.ProgramKitPublicAnalyzerReceiptNonce";

    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        var nonce = context.AnalyzerConfigOptionsProvider.Select(
            static (options, _) =>
                options.GlobalOptions.TryGetValue(
                    NonceProperty,
                    out var value)
                    ? value
                    : string.Empty);
        context.RegisterSourceOutput(
            nonce,
            static (output, value) =>
            {
                if (!IsLowerHexNonce(value))
                {
                    return;
                }

                var source = string.Concat(
                    "// <auto-generated program-kit>",
                    Environment.NewLine,
                    "// public-analyzer-receipt:generated-source-contract:",
                    value,
                    Environment.NewLine);
                output.AddSource(
                    string.Concat(
                        "ProgramKitGenerated/PublicAnalyzerReceipt/",
                        "GeneratedSourceContractReceipt.",
                        value,
                        ".cs"),
                    SourceText.From(source, Encoding.UTF8));
            });
    }

    private static bool IsLowerHexNonce(string value) =>
        value.Length == 32 &&
        value.All(static character =>
            character is (>= '0' and <= '9') or
                (>= 'a' and <= 'f'));
}
