using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Orbyss.ProgramKit.GeneratedSourceContract.Operations.Analysis;

/// <summary>
/// Enforces only the explicitly selected public Program Kit generated-source
/// convention. It contains no Program Kit repository policy.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class GeneratedSourceContractAnalyzer : DiagnosticAnalyzer
{
    private const string ActivationProperty =
        "build_property.ProgramKitGeneratedSourceContract";
    private const string ActivationValue = "1.0.0";
    private const string GeneratedRoot = "ProgramKitGenerated";
    private const string OwnershipHeader = "// <auto-generated program-kit>";

    private static readonly DiagnosticDescriptor GeneratedSourceConvention =
        new(
            "PKCC001",
            "Generated source must conform to its selected public contract",
            "Source '{0}' must pair the exact Program Kit ownership header with " +
            "the exact 'ProgramKitGenerated/<intent>/<file>.cs' logical path",
            "ProgramKit.GeneratedSourceContract",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true,
            description:
                "Enforces only the opted-in public generated-source path/header pairing.");

    /// <inheritdoc />
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        [GeneratedSourceConvention];

    /// <inheritdoc />
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(
            GeneratedCodeAnalysisFlags.Analyze |
            GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.EnableConcurrentExecution();
        context.RegisterCompilationStartAction(RegisterOptedInAnalysis);
    }

    private static void RegisterOptedInAnalysis(
        CompilationStartAnalysisContext context)
    {
        var globalOptions =
            context.Options.AnalyzerConfigOptionsProvider.GlobalOptions;
        if (!globalOptions.TryGetValue(
                ActivationProperty,
                out var selectedVersion) ||
            !string.Equals(
                selectedVersion,
                ActivationValue,
                StringComparison.Ordinal))
        {
            return;
        }

        context.RegisterSyntaxTreeAction(AnalyzeSyntaxTree);
    }

    private static void AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context)
    {
        var sourceText = context.Tree.GetText(context.CancellationToken);
        var hasHeader = HasExactOwnershipHeader(sourceText);
        var hasContractPath = HasExactContractPath(context.Tree.FilePath);
        if (hasHeader == hasContractPath)
        {
            return;
        }

        context.ReportDiagnostic(
            Diagnostic.Create(
                GeneratedSourceConvention,
                context.Tree.GetRoot(context.CancellationToken).GetLocation(),
                DisplayPath(context.Tree.FilePath)));
    }

    private static bool HasExactOwnershipHeader(SourceText sourceText) =>
        sourceText.Lines.Count > 0 &&
        string.Equals(
            sourceText.ToString(sourceText.Lines[0].Span),
            OwnershipHeader,
            StringComparison.Ordinal);

    private static bool HasExactContractPath(string sourcePath)
    {
        if (string.IsNullOrWhiteSpace(sourcePath))
        {
            return false;
        }

        var normalized = sourcePath.Replace('\\', '/');
        var segments = normalized.Split(
            '/',
            StringSplitOptions.RemoveEmptyEntries);
        for (var index = 0; index < segments.Length; index++)
        {
            if (!string.Equals(
                    segments[index],
                    GeneratedRoot,
                    StringComparison.Ordinal))
            {
                continue;
            }

            return index + 2 == segments.Length - 1 &&
                !string.IsNullOrWhiteSpace(segments[index + 1]) &&
                segments[index + 1] is not "." and not ".." &&
                segments[index + 2].EndsWith(
                    ".cs",
                    StringComparison.Ordinal) &&
                segments[index + 2].Length > ".cs".Length;
        }

        return false;
    }

    private static string DisplayPath(string sourcePath) =>
        string.IsNullOrWhiteSpace(sourcePath)
            ? "<pathless>"
            : sourcePath.Replace('\\', '/');
}
