<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IsPackable>false</IsPackable>
    <RootNamespace>Orbyss.ProgramKit.Artifacts.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Analyzer Include="$(NuGetPackageRoot)mstest.analyzers\4.3.2\analyzers\dotnet\cs\MSTest.Analyzers.dll">
      <NuGetPackageId>MSTest.Analyzers</NuGetPackageId>
      <NuGetPackageVersion>4.3.2</NuGetPackageVersion>
    </Analyzer>
    <Compile Include="Features\MisalignedFeatureTests.cs" />
  </ItemGroup>
</Project>
