// <auto-generated program-kit>
#nullable enable

namespace GeneratedHost.Hosting;

/// <summary>
/// Consumer-owned dispatch boundary for one exact projected operation.
/// The implementation owns request, response, and operation behavior.
/// </summary>
public interface IProgramKitFastEndpointOperationDispatcher
{
    /// <summary>Dispatches one exact operation through the current HTTP context.</summary>
    global::System.Threading.Tasks.ValueTask DispatchAsync(
        string operationRevision,
        global::Microsoft.AspNetCore.Http.HttpContext context,
        global::System.Threading.CancellationToken cancellationToken);
}
