// <auto-generated program-kit>
#nullable enable

using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitMappedTransportFailureHandler :
    IExceptionHandler
{
    private readonly IProblemDetailsService service;

    public ProgramKitMappedTransportFailureHandler(
        IProblemDetailsService service)
    {
        this.service = service;
    }

    public async ValueTask<bool> TryHandleAsync(
        HttpContext context,
        Exception exception,
        CancellationToken cancellationToken)
    {
        if (context.Response.HasStarted ||
            exception is not InvalidOperationException)
        {
            return false;
        }

        context.Response.StatusCode = StatusCodes.Status409Conflict;
        return await service.TryWriteAsync(new ProblemDetailsContext
        {
            HttpContext = context,
            ProblemDetails = new ProblemDetails
            {
                Status = StatusCodes.Status409Conflict,
                Type = "https://errors.orbyss.test/conflict",
                Title = "Conflict",
                Detail = "The request conflicts with the current state.",
                Instance = context.Request.Path,
            },
        });
    }
}
