// <auto-generated program-kit>
#nullable enable

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitFastEndpointFailure :
    global::FastEndpoints.EndpointWithoutRequest,
    global::FastEndpoints.IEndpoint
{
    public override void Configure()
    {
        Verbs("GET");
        Routes("/failure");
        AllowAnonymous();
        DontCatchExceptions();
    }

    public override async global::System.Threading.Tasks.Task HandleAsync(
        global::System.Threading.CancellationToken cancellationToken)
    {
        var dispatcher =
            Resolve<IProgramKitFastEndpointOperationDispatcher>();
        await dispatcher.DispatchAsync(
            "failure",
            HttpContext,
            cancellationToken);
    }
}
