// <auto-generated program-kit>
#nullable enable

namespace GeneratedHost.Hosting;

/// <summary>
/// Activates the exact FastEndpoints host adapter for one selected shell.
/// </summary>
[global::CShells.Features.ShellFeature(
    "ProgramKitFastEndpoints",
    DependsOn = ["FastEndpoints"])]
public sealed class ProgramKitFastEndpointsFeature :
    global::CShells.FastEndpoints.Features.IFastEndpointsShellFeature
{
    /// <inheritdoc />
    public void ConfigureServices(
        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
    }
}
