<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ProgramKitFeatureIdentity>PriceCalculator.Access.Api</ProgramKitFeatureIdentity>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="ProgramKitFeatureIdentity" />
  </ItemGroup>
</Project>
