// <auto-generated program-kit>
#nullable enable

namespace Orbyss.ProgramKit.TelemetryConsumerFixture.Hosting;

/// <summary>Stable typed category for fixture operation diagnostics.</summary>
public sealed class OrbyssProgramKitFixtureOperationsCategory
{
    private OrbyssProgramKitFixtureOperationsCategory()
    {
    }
}
