// <auto-generated program-kit>
#nullable enable

namespace Orbyss.ProgramKit.TelemetryConsumerFixture.Hosting;

/// <summary>Startup-fixed, validated options for reviewed telemetry export.</summary>
public sealed class ProgramKitTelemetryOptions
{
    /// <summary>Gets or sets the absolute OTLP collector endpoint.</summary>
    public Uri Endpoint { get; set; } = null!;

    /// <summary>Parses the required endpoint without exposing secret-bearing configuration.</summary>
    public static Uri ParseEndpoint(string? value)
    {
        if (!Uri.TryCreate(value, UriKind.Absolute, out var endpoint) ||
            (endpoint.Scheme != Uri.UriSchemeHttp &&
             endpoint.Scheme != Uri.UriSchemeHttps))
        {
            throw new Microsoft.Extensions.Options.OptionsValidationException(
                "ProgramKitTelemetry",
                typeof(ProgramKitTelemetryOptions),
                ["The OTLP endpoint configuration reference must be an absolute HTTP or HTTPS URI."]);
        }

        return endpoint;
    }
}
