// <auto-generated program-kit>
#nullable enable
using System.Diagnostics;
using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;

namespace Orbyss.ProgramKit.TelemetryConsumerFixture.Hosting;

/// <summary>Stable provider-neutral telemetry emission surface.</summary>
public static partial class ProgramKitTelemetry
{
    private static readonly ActivitySource OperationsSource =
        new("Orbyss.ProgramKit.Fixture.Operations", "1.0.0");
    private static readonly Meter OperationsMeter =
        new("Orbyss.ProgramKit.Fixture.Operations", "1.0.0");
    private static readonly Counter<long> OperationCount =
        OperationsMeter.CreateCounter<long>(
            "operation.count",
            "{operation}",
            "Completed operations.");
    private static readonly Histogram<double> OperationDuration =
        OperationsMeter.CreateHistogram<double>(
            "operation.duration",
            "s",
            "Operation duration.");

    /// <summary>Emits one stable structured operation-started event.</summary>
    [LoggerMessage(
        EventId = 1001,
        EventName = "OperationStarted",
        Level = LogLevel.Information,
        Message = "Operation {operationIdentity} started with correlation {correlationId}.")]
    public static partial void OperationStarted(
        ILogger<OrbyssProgramKitFixtureOperationsCategory> logger,
        string operationIdentity,
        string correlationId);

    /// <summary>Begins one bounded correlation scope.</summary>
    public static IDisposable? BeginOperationStartedScope(
        ILogger<OrbyssProgramKitFixtureOperationsCategory> logger,
        string operationIdentity,
        string correlationId) =>
        logger.BeginScope(new Dictionary<string, object?>
        {
            ["operation.identity"] = operationIdentity,
            ["correlation.id"] = correlationId,
        });

    /// <summary>Starts one Program Kit-owned internal operation activity.</summary>
    public static Activity? StartOperation() =>
        OperationsSource.StartActivity(
            "operation.execute",
            ActivityKind.Internal);

    /// <summary>Records a bounded operation outcome and duration.</summary>
    public static void RecordOperation(string outcome, double durationSeconds)
    {
        if (outcome is not ("succeeded" or "failed" or "cancelled"))
        {
            throw new ArgumentOutOfRangeException(
                nameof(outcome),
                "Outcome must be one reviewed bounded value.");
        }

        TagList tags = new()
        {
            { "operation.outcome", outcome },
        };
        OperationCount.Add(1, tags);
        OperationDuration.Record(durationSeconds, tags);
    }
}
