// <auto-generated program-kit>
#nullable enable
using System.Diagnostics;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using OpenTelemetry;
using OpenTelemetry.Context.Propagation;
using OpenTelemetry.Exporter;
using OpenTelemetry.Logs;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace Orbyss.ProgramKit.TelemetryConsumerFixture.Hosting;

/// <summary>Exact startup-fixed OpenTelemetry 1.17.0 host composition.</summary>
public static class TelemetryComposition
{
    /// <summary>Adds reviewed logging, tracing, metrics, instrumentation, and bounded OTLP export.</summary>
    public static void AddReviewedTelemetry(IHostApplicationBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var endpoint = ProgramKitTelemetryOptions.ParseEndpoint(
            builder.Configuration["Telemetry:Otlp:Endpoint"]);
        builder.Services.AddOptions<ProgramKitTelemetryOptions>()
            .Configure(options => options.Endpoint = endpoint)
            .Validate(
                static options => options.Endpoint.IsAbsoluteUri,
                "The OTLP endpoint must be absolute.")
            .ValidateOnStart();
        builder.Logging.AddConfiguration(
            builder.Configuration.GetSection("Logging"));
        builder.Services.Configure<HostOptions>(
            options => options.ShutdownTimeout =
                TimeSpan.FromMilliseconds(5000));
        Activity.DefaultIdFormat = ActivityIdFormat.W3C;
        Activity.ForceDefaultIdFormat = true;
        Sdk.SetDefaultTextMapPropagator(new TraceContextPropagator());
        builder.Logging.AddJsonConsole();
        builder.Services.AddOpenTelemetry()
            .ConfigureResource(resource => resource.AddService(
                "orbyss.program-kit.telemetry-fixture",
                "orbyss.program-kit",
                "1.0.0"))
            .WithTracing(tracing =>
            {
                tracing.AddSource("Orbyss.ProgramKit.Fixture.Operations");
                tracing.SetSampler(
                    new ParentBasedSampler(
                        new TraceIdRatioBasedSampler(1.0)));
                tracing.AddAspNetCoreInstrumentation(options =>
                {
                    options.RecordException = true;
                });
                tracing.AddHttpClientInstrumentation();
                tracing.AddOtlpExporter(options =>
                {
                    ConfigureExporter(endpoint, options);
                    options.ExportProcessorType = ExportProcessorType.Batch;
                    options.BatchExportProcessorOptions.MaxQueueSize = 64;
                    options.BatchExportProcessorOptions.MaxExportBatchSize = 16;
                    options.BatchExportProcessorOptions.ScheduledDelayMilliseconds = 100;
                    options.BatchExportProcessorOptions.ExporterTimeoutMilliseconds = 100;
                });
            })
            .WithMetrics(metrics =>
            {
                metrics.AddMeter("Orbyss.ProgramKit.Fixture.Operations");
                metrics.AddAspNetCoreInstrumentation();
                metrics.AddHttpClientInstrumentation();
                metrics.AddOtlpExporter((options, reader) =>
                {
                    ConfigureExporter(endpoint, options);
                    reader.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 100;
                    reader.PeriodicExportingMetricReaderOptions.ExportTimeoutMilliseconds = 100;
                });
            })
            .WithLogging(logging =>
            {
                logging.AddOtlpExporter((options, processor) =>
                {
                    ConfigureExporter(endpoint, options);
                    processor.BatchExportProcessorOptions.MaxQueueSize = 64;
                    processor.BatchExportProcessorOptions.MaxExportBatchSize = 16;
                    processor.BatchExportProcessorOptions.ScheduledDelayMilliseconds = 100;
                    processor.BatchExportProcessorOptions.ExporterTimeoutMilliseconds = 100;
                });
            }, options =>
            {
                options.IncludeFormattedMessage = false;
                options.IncludeScopes = true;
                options.ParseStateValues = true;
            });
    }

    private static void ConfigureExporter(
        Uri endpoint,
        OtlpExporterOptions options)
    {
        options.Endpoint = endpoint;
        options.Protocol = OtlpExportProtocol.Grpc;
        options.TimeoutMilliseconds = 100;
    }
}
