<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Orbyss.ProgramKit.FastEndpointsConsumerFixture</AssemblyName>
    <RootNamespace>GeneratedHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CShells.FastEndpoints" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
</Project>
