using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Orbyss.ProgramKit.CSharpGate.GeneratedSourceProbe.Composition;

/// <summary>Emits a deterministic source specimen for C# gate conformance.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class GeneratedSourceProbeGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var gateCase = context.AnalyzerConfigOptionsProvider.Select(
            static (options, _) =>
                options.GlobalOptions.TryGetValue(
                    "build_property.GeneratedGateCase",
                    out var configured)
                    ? configured
                    : "Valid");

        context.RegisterSourceOutput(
            gateCase,
            static (productionContext, configured) =>
            {
                var source = configured switch
                {
                    "Invalid" => """
                      // <auto-generated program-kit>
                      namespace Orbyss.ProgramKit.GeneratedProbe.Hosting;

                      /// <summary>Generated host fixture.</summary>
                      public sealed record GeneratedHost;

                      /// <summary>Second generated type that must be rejected.</summary>
                      public sealed record UnexpectedGeneratedHost;
                      """,
                    "NoHeader" => """
                      namespace Orbyss.ProgramKit.GeneratedProbe.Hosting;

                      /// <summary>Generated host fixture.</summary>
                      public sealed record GeneratedHost;
                      """,
                    "MalformedHeader" => """
                      // <auto-generated program-kit> suffix
                      namespace Orbyss.ProgramKit.GeneratedProbe.Hosting;

                      /// <summary>Generated host fixture.</summary>
                      public sealed record GeneratedHost;
                      """,
                    _ => """
                      // <auto-generated program-kit>
                      namespace Orbyss.ProgramKit.GeneratedProbe.Hosting;

                      /// <summary>Generated host fixture.</summary>
                      public sealed record GeneratedHost;
                      """,
                };

                var hintName = configured switch
                {
                    "WrongHint" => "GeneratedHost.cs",
                    "NestedHint" =>
                        "ProgramKitGenerated/Hosting/Internal/GeneratedHost.cs",
                    _ => "ProgramKitGenerated/Hosting/GeneratedHost.cs",
                };
                productionContext.AddSource(
                    hintName,
                    SourceText.From(source, Encoding.UTF8));
            });
    }
}
