name: program-kit-application

services:
  application:
    image: program-kit-consumer:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CShells__Shells__default__Configuration__ProgramKit__Web__BackchannelAuthority: http://program-kit-identity:8080/realms/program-kit
    networks:
      - program-kit-local
    ports:
      - "5000:8080"

networks:
  program-kit-local:
    name: program-kit-local
    external: true
