// <auto-generated program-kit>
#nullable enable
using System.Collections.Concurrent;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace GeneratedOAuthServiceClients.Operations;

public sealed class OAuthServiceClientProbe(HttpClient httpClient)
{
    public const string TokenExchangeGrant =
        "urn:ietf:params:oauth:grant-type:token-exchange";
    private readonly ConcurrentDictionary<string, OAuthAccessToken> cache =
        new(StringComparer.Ordinal);

    public async ValueTask<(OAuthAccessToken Token, OAuthOutcomeEvidence Evidence)> ClientCredentialsAsync(
        OAuthProfile profile,
        string clientSecret,
        CancellationToken cancellationToken) =>
        await SendAsync(profile, clientSecret, null, null, cancellationToken);

    public async ValueTask<(OAuthAccessToken Token, OAuthOutcomeEvidence Evidence)> ExchangeAsync(
        OAuthProfile profile,
        string clientSecret,
        OAuthSourceToken subject,
        OAuthSourceToken? actor,
        bool delegation,
        CancellationToken cancellationToken)
    {
        if ((delegation && actor is null) || (!delegation && actor is not null))
        {
            throw new InvalidOperationException(
                "Delegation requires an actor; impersonation forbids one.");
        }
        if (actor is not null &&
            string.Equals(
                actor.ProvenanceIdentity,
                subject.ProvenanceIdentity,
                StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "Subject and actor provenance must remain distinct.");
        }
        return await SendAsync(
            profile,
            clientSecret,
            subject,
            actor,
            cancellationToken);
    }

    public static string CreateCacheKey(
        OAuthProfile profile,
        OAuthSourceToken? subject,
        OAuthSourceToken? actor)
    {
        var dimensions = string.Join(
            "\u001f",
            profile.ClientName,
            profile.ClientId,
            profile.Resource.AbsoluteUri,
            profile.Audience,
            profile.Scope,
            profile.RequestedTokenType,
            profile.ExpectedIssuedTokenType,
            subject?.ProvenanceIdentity,
            subject?.Type,
            Digest(subject?.Value),
            actor?.ProvenanceIdentity,
            actor?.Type,
            Digest(actor?.Value));
        return Convert.ToHexString(
            SHA256.HashData(Encoding.UTF8.GetBytes(dimensions)));
    }

    private async ValueTask<(OAuthAccessToken, OAuthOutcomeEvidence)> SendAsync(
        OAuthProfile profile,
        string clientSecret,
        OAuthSourceToken? subject,
        OAuthSourceToken? actor,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var key = CreateCacheKey(profile, subject, actor);
        if (cache.TryGetValue(key, out var cached) &&
            cached.ExpiresAt > DateTimeOffset.UtcNow.AddSeconds(profile.ExpirySkewSeconds))
        {
            return (cached, new OAuthOutcomeEvidence(profile.ClientName, "cache-hit"));
        }

        var form = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["grant_type"] = subject is null ? "client_credentials" : TokenExchangeGrant,
            ["client_id"] = profile.ClientId,
            ["resource"] = profile.Resource.AbsoluteUri,
            ["audience"] = profile.Audience,
            ["scope"] = profile.Scope,
        };
        if (subject is not null)
        {
            form["requested_token_type"] = profile.RequestedTokenType;
            form["subject_token"] = subject.Value;
            form["subject_token_type"] = subject.Type;
            if (actor is not null)
            {
                form["actor_token"] = actor.Value;
                form["actor_token_type"] = actor.Type;
            }
        }

        using var request = new HttpRequestMessage(HttpMethod.Post, profile.TokenEndpoint)
        {
            Content = new FormUrlEncodedContent(form),
        };
        request.Headers.Authorization = new AuthenticationHeaderValue(
            "Basic",
            Convert.ToBase64String(
                Encoding.UTF8.GetBytes(
                    string.Concat(profile.ClientId, ":", clientSecret))));
        using var response = await httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            throw new InvalidOperationException(
                string.Concat("OAuth endpoint rejected profile ", profile.ClientName, "."));
        }

        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        using var json = await JsonDocument.ParseAsync(
            stream,
            cancellationToken: cancellationToken);
        var root = json.RootElement;
        var token = root.GetProperty("access_token").GetString();
        var issuedType = root.GetProperty("issued_token_type").GetString();
        var scope = root.GetProperty("scope").GetString();
        var expiresIn = root.GetProperty("expires_in").GetInt32();
        if (string.IsNullOrWhiteSpace(token) ||
            issuedType != profile.ExpectedIssuedTokenType ||
            scope != profile.Scope ||
            expiresIn is <= 0 ||
            expiresIn > profile.MaximumLifetimeSeconds)
        {
            throw new InvalidOperationException(
                string.Concat("OAuth response violated profile ", profile.ClientName, "."));
        }

        var result = new OAuthAccessToken(
            token,
            issuedType,
            DateTimeOffset.UtcNow.AddSeconds(expiresIn));
        cache[key] = result;
        return (result, new OAuthOutcomeEvidence(profile.ClientName, "accepted"));
    }

    private static string Digest(string? value) =>
        value is null
            ? "-"
            : Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));
}
