// <auto-generated program-kit>
#nullable enable

namespace GeneratedOAuthServiceClients.Operations;

public sealed record OAuthSourceToken(
    string Value,
    string Type,
    string ProvenanceIdentity);
