// <auto-generated program-kit>
#nullable enable

namespace GeneratedOAuthServiceClients.Operations;

public sealed record OAuthProfile(
    string ClientName,
    Uri TokenEndpoint,
    string ClientId,
    Uri Resource,
    string Audience,
    string Scope,
    string RequestedTokenType,
    string ExpectedIssuedTokenType,
    int MaximumLifetimeSeconds,
    int ExpirySkewSeconds);
