// <auto-generated program-kit>
#nullable enable

namespace GeneratedOAuthServiceClients.Operations;

public sealed record OAuthAccessToken(
    string Value,
    string Type,
    DateTimeOffset ExpiresAt);
