"""Compile with the published analyzer and selected SDK; execute runtime counterexamples."""
from __future__ import annotations
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / 'extensions/program-kit-dotnet/templates/dotnet/files'


def run(command, root, env, expected=0):
    result = subprocess.run(command, cwd=root, env=env, capture_output=True, text=True, encoding='utf-8', timeout=180)
    if expected is not None and result.returncode != expected:
        raise AssertionError(' '.join(command) + '\n' + result.stdout + result.stderr)
    return result


def main():
    artifact = ROOT / 'artifacts/dotnet-engineering'
    artifact.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env.update(DOTNET_CLI_HOME=str(artifact / 'cli'), NUGET_PACKAGES=str(artifact / 'packages'),
               DOTNET_CLI_TELEMETRY_OPTOUT='1', DOTNET_SKIP_FIRST_TIME_EXPERIENCE='1', DOTNET_NOLOGO='1')
    package = next(n.attrib['Version'] for n in ET.parse(TEMPLATE / '.program-kit/eng/ProgramKit.Packages.props').iter('PackageVersion')
                   if n.attrib['Include'] == 'Orbyss.Foundation.Analyzers')
    sdk = json.loads((TEMPLATE / 'global.json').read_text())['sdk']
    with tempfile.TemporaryDirectory(prefix='engineering-', dir=artifact) as name:
        root = Path(name)
        (root / 'global.json').write_text(json.dumps({'sdk': sdk}))
        (root / 'NuGet.config').write_text('<configuration><packageSources><clear/><add key="nuget.org" value="https://api.nuget.org/v3/index.json"/></packageSources></configuration>')
        (root / 'Probe.csproj').write_text(f'''<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
  <AnalysisLevel>latest</AnalysisLevel><EnableNETAnalyzers>true</EnableNETAnalyzers><GenerateDocumentationFile>true</GenerateDocumentationFile><FoundationFeatureIdentity>Expected</FoundationFeatureIdentity>
  <EnableDefaultCompileItems>false</EnableDefaultCompileItems><OutputType>Library</OutputType></PropertyGroup>
  <ItemGroup><PackageReference Include="Orbyss.Foundation.Analyzers" Version="{package}" PrivateAssets="all" />
  <FrameworkReference Include="Microsoft.AspNetCore.App" /><Compile Include="$(Case)/*.cs" />
  <CompilerVisibleProperty Include="FoundationFeatureIdentity" /></ItemGroup></Project>''')
        shutil.copyfile(TEMPLATE / '.editorconfig', root / '.editorconfig')
        bad = root / 'bad'; bad.mkdir()
        (bad / 'Bad.cs').write_text('''using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
namespace Cases;
public sealed class Bad : CShells.Features.IShellFeature
{
 private static int Helper() => 1;
 public static int Operation() { Four(1, 2, 3, 4); return Helper(); }
 public static void Four(int a, int b, int c, int d) { }
 public static ValueTask Obtain() => new ValueTask(Task.Delay(1));
 public static async Task ValueUse() { var value = Obtain(); await value; await value; }
 public static Task Dropped(CancellationToken token) => Task.Delay(1);
 public static void Register(IServiceCollection services) => services.AddHostedService<Worker>();
}
public sealed class Other { }
''')
        # Symbol-shape controls exercise the analyzer's documented symbol rule, not real CShells activation.
        (bad / 'IShellFeature.cs').write_text('namespace CShells.Features; public interface IShellFeature { }')
        (bad / 'Worker.cs').write_text('public sealed class Worker : Microsoft.Extensions.Hosting.BackgroundService { protected override Task ExecuteAsync(CancellationToken token) => Task.CompletedTask; }')
        good = root / 'good'; good.mkdir()
        (good / 'Pure.cs').write_text('''namespace Cases;
/// <summary>Provides a pure typed transformation with no artificial DI boundary.</summary>
internal static class Pure
{
 /// <summary>Returns the larger input.</summary>
 internal static int Max(int left, int right) => Math.Max(left, right);
 /// <summary>Observes a single-consumption value.</summary>
 internal static async Task Consume() { var value = new ValueTask(Task.CompletedTask); await value; }
 /// <summary>Passes cancellation to owned work.</summary>
 internal static Task Wait(CancellationToken token) => Task.Delay(1, token);
}
''')
        (good / 'Generated.g.cs').write_text('// <auto-generated/>\nclass One { } class Two { }')
        (good / 'Suppressed.cs').write_text('''#pragma warning disable ORB1005 // Fixture proves explicit scoped suppression; no production waiver implied.
internal sealed class Suppressed { }
#pragma warning restore ORB1005
''')
        run(['dotnet', 'restore', 'Probe.csproj', '--configfile', 'NuGet.config', '--verbosity', 'quiet'], root, env)
        command = ['dotnet', 'build', 'Probe.csproj', '--no-restore', '--no-incremental', '--verbosity', 'quiet']
        result = run(command + ['-p:Case=bad', '-p:ErrorLog=bad.sarif'], root, env, expected=None)
        if result.returncode == 0:
            raise AssertionError('Bad analyzer fixture unexpectedly compiled')
        sarif = json.loads((root / 'bad.sarif').read_text(encoding='utf-8-sig'))
        diagnostics = [d for r in sarif['runs'] for d in r.get('results', [])]
        levels = {d['ruleId']: d.get('level') for d in diagnostics}
        required = {'ORB1001', 'ORB1003', 'ORB1004', 'ORB1005', 'ORB1006', 'CA2012', 'CA2016'}
        if not required <= levels.keys() or any(levels[rule] != 'error' for rule in required):
            raise AssertionError(f'Missing expected error diagnostics: {required - levels.keys()}; {levels}')
        if levels.get('ORB1002') != 'note':
            raise AssertionError(f'Policy B must remain a suggestion, got {levels.get("ORB1002")}')
        run(command + ['-p:Case=good', '-p:ErrorLog=good.sarif'], root, env)
        clean = json.loads((root / 'good.sarif').read_text(encoding='utf-8-sig'))
        unexpected = [d for r in clean['runs'] for d in r.get('results', []) if d['ruleId'] in required
                      and d.get('suppressionStates') != ['suppressedInSource']]
        if unexpected:
            raise AssertionError(f'Legitimate/generated/scoped-suppression fixture failed: {unexpected}')
        runtime = root / 'runtime'; runtime.mkdir()
        shutil.copytree(ROOT / 'tests/fixtures/dotnet-engineering', runtime, dirs_exist_ok=True)
        run(['dotnet', 'run', '--project', str(runtime / 'EngineeringCases.csproj'), '--', str(artifact / 'runtime.xml')], root, env)
        results = ET.parse(artifact / 'runtime.xml')
        if not list(results.iter('testcase')) or list(results.iter('failure')):
            raise AssertionError('Runtime evidence did not pass')
        nupkg = artifact / f'packages/orbyss.foundation.analyzers/{package}/orbyss.foundation.analyzers.{package}.nupkg'
        receipt = {'sdk': sdk, 'analyzerVersion': package, 'analyzerSha256': hashlib.sha256(nupkg.read_bytes()).hexdigest(),
                   'editorConfigSha256': hashlib.sha256((TEMPLATE / '.editorconfig').read_bytes()).hexdigest(),
                   'diagnostics': levels, 'runtimeCases': [c.attrib['name'] for c in results.iter('testcase')]}
        (artifact / 'verification.json').write_text(json.dumps(receipt, indent=2) + '\n')
        print(f'Published analyzer/SDK positive and negative controls passed; {len(receipt["runtimeCases"])} runtime cases.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
