using System.Text;
using Microsoft.Build.Framework;
using Orbyss.ProgramKit.GeneratedOutputIntegrity.Build.Composition;

namespace Orbyss.ProgramKit.GeneratedOutputIntegrity.Build.Operations.Execution;

/// <summary>Verifies generated bytes and emits the source attestation required by the host.</summary>
public sealed class VerifyGeneratedOutputTask : Microsoft.Build.Utilities.Task
{
    /// <summary>Gets or sets the complete generated host root.</summary>
    [Required]
    public string RootPath { get; set; } = string.Empty;

    /// <summary>Gets or sets the intermediate source-attestation path.</summary>
    [Required]
    public string AttestationPath { get; set; } = string.Empty;

    /// <inheritdoc />
    public override bool Execute()
    {
        try
        {
            var verifier =
                GeneratedOutputIntegrityBuildComposition.CreateVerifier();
            var result = verifier.VerifyAsync(
                    RootPath,
                    CancellationToken.None)
                .AsTask()
                .GetAwaiter()
                .GetResult();
            if (!result.IsValid)
            {
                foreach (var issue in result.Issues)
                {
                    Log.LogError(
                        subcategory: "ProgramKitGeneratedOutputIntegrity",
                        errorCode: "PKINT100",
                        helpKeyword: null,
                        file: issue.Path,
                        lineNumber: 0,
                        columnNumber: 0,
                        endLineNumber: 0,
                        endColumnNumber: 0,
                        message: issue.Message);
                }

                return false;
            }

            var fullAttestationPath = Path.GetFullPath(AttestationPath);
            var parent = Path.GetDirectoryName(fullAttestationPath);
            if (string.IsNullOrWhiteSpace(parent))
            {
                Log.LogError("The Program Kit integrity attestation path has no parent.");
                return false;
            }

            Directory.CreateDirectory(parent);
            File.WriteAllText(
                fullAttestationPath,
                """
                // <auto-generated program-kit>
                namespace GeneratedHost.Hosting;

                internal abstract class ProgramKitGeneratedIntegrityAttestation;

                """,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(
                exception,
                showStackTrace: false,
                showDetail: false,
                file: RootPath);
            return false;
        }
    }
}
