using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Orbyss.ProgramKit.CSharpGate.Generation;

/// <summary>
/// Emits a build-intermediate receipt that can exist only when the configured
/// Program Kit analyzer and generator assembly actually ran in the compiler.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ProgramKitCompilerInvocationReceiptGenerator :
    IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        var nonce = context.AnalyzerConfigOptionsProvider.Select(
            static (options, _) =>
                options.GlobalOptions.TryGetValue(
                    "build_property.ProgramKitCompilerInvocationNonce",
                    out var value)
                    ? value
                    : string.Empty);
        context.RegisterSourceOutput(
            nonce,
            static (output, value) =>
            {
                if (value.Length != 32 ||
                    value.Any(static character =>
                        character is not (>= '0' and <= '9') and not
                            (>= 'a' and <= 'f')))
                {
                    return;
                }

                var source = string.Concat(
                    "// <auto-generated program-kit>",
                    "\n",
                    "// compiler-executed:program-kit",
                    "\n");
                output.AddSource(
                    "ProgramKitGenerated/CompilerInvocation/" +
                    "ProgramKitCompilerInvocationReceipt.cs",
                    SourceText.From(source, Encoding.UTF8));
            });
    }
}
