using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Binding;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleSettingsRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        projection.Commands
            .Select(command => new GeneratedOutput(
                Path(command, "Settings"),
                DotNetSourceText.Utf8(Render(command))))
            .ToImmutableArray();

    private static string Path(
        DotNetConsoleCommandProjection command,
        string suffix) =>
        string.Concat(
            "ProgramKitGenerated/Commands/",
            command.Symbol,
            "/",
            command.Symbol,
            suffix,
            ".cs");

    private static string Render(DotNetConsoleCommandProjection command)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Commands;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "internal sealed class ",
                command.SettingsTypeName,
                " : global::Spectre.Console.Cli.CommandSettings"));
        DotNetConsoleRendering.Line(builder, 0, "{");
        foreach (var value in command.Values.OrderBy(
                     static item => item.ConstructorPosition))
        {
            RenderValue(builder, value);
        }

        RenderValidation(builder, command);
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static void RenderValidation(
        StringBuilder builder,
        DotNetConsoleCommandProjection command)
    {
        DotNetConsoleRendering.Line(
            builder,
            1,
            "public override global::Spectre.Console.ValidationResult Validate()");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "var messages = new global::System.Collections.Generic.List<string>();");
        foreach (var value in command.Values.OrderBy(
                     static item => item.ConstructorPosition))
        {
            var count = value.Repeated
                ? string.Concat(
                    value.PropertyName,
                    "?.Length ?? 0")
                : string.Concat(
                    value.PropertyName,
                    "Specified ? 1 : 0");
            DotNetConsoleRendering.Line(
                builder,
                2,
                string.Concat("var count", value.ConstructorPosition, " = ", count, ";"));
            DotNetConsoleRendering.Line(
                builder,
                2,
                string.Concat(
                    "if (count",
                    value.ConstructorPosition,
                    " < ",
                    value.MinimumOccurrences,
                    " || count",
                    value.ConstructorPosition,
                    " > ",
                    value.MaximumOccurrences,
                    ")"));
            DotNetConsoleRendering.Line(builder, 2, "{");
            DotNetConsoleRendering.Line(
                builder,
                3,
                string.Concat(
                    "messages.Add(",
                    DotNetSourceText.CSharpLiteral(
                        string.Concat(
                            "Occurrence constraint failed: ",
                            value.SourceName,
                            ".")),
                    ");"));
            DotNetConsoleRendering.Line(builder, 2, "}");
        }

        var bySource = command.Values.ToDictionary(
            static value => value.SourceName,
            StringComparer.Ordinal);
        foreach (var value in command.Values.OrderBy(
                     static item => item.SourceName,
                     StringComparer.Ordinal))
        {
            foreach (var conflict in value.Conflicts
                         .Where(conflict =>
                             string.CompareOrdinal(
                                 value.SourceName,
                                 conflict) < 0)
                         .Order(StringComparer.Ordinal))
            {
                var other = bySource[conflict];
                DotNetConsoleRendering.Line(
                    builder,
                    2,
                    string.Concat(
                        "if (",
                        value.PropertyName,
                        "Specified && ",
                        other.PropertyName,
                        "Specified)"));
                DotNetConsoleRendering.Line(builder, 2, "{");
                DotNetConsoleRendering.Line(
                    builder,
                    3,
                    string.Concat(
                        "messages.Add(",
                        DotNetSourceText.CSharpLiteral(
                            string.Concat(
                                "Conflicting options: ",
                                value.SourceName,
                                " and ",
                                conflict,
                                ".")),
                        ");"));
                DotNetConsoleRendering.Line(builder, 2, "}");
            }

            foreach (var prerequisite in value.Prerequisites
                         .Order(StringComparer.Ordinal))
            {
                var other = bySource[prerequisite];
                DotNetConsoleRendering.Line(
                    builder,
                    2,
                    string.Concat(
                        "if (",
                        value.PropertyName,
                        "Specified && !",
                        other.PropertyName,
                        "Specified)"));
                DotNetConsoleRendering.Line(builder, 2, "{");
                DotNetConsoleRendering.Line(
                    builder,
                    3,
                    string.Concat(
                        "messages.Add(",
                        DotNetSourceText.CSharpLiteral(
                            string.Concat(
                                "Option prerequisite missing: ",
                                value.SourceName,
                                " requires ",
                                prerequisite,
                                ".")),
                        ");"));
                DotNetConsoleRendering.Line(builder, 2, "}");
            }
        }

        DotNetConsoleRendering.Line(
            builder,
            2,
            "return messages.Count == 0");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "? global::Spectre.Console.ValidationResult.Success()");
        DotNetConsoleRendering.Line(
            builder,
            3,
            ": global::Spectre.Console.ValidationResult.Error(");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "string.Join(global::System.Environment.NewLine, messages));");
        DotNetConsoleRendering.Line(builder, 1, "}");
    }

    private static void RenderValue(
        StringBuilder builder,
        DotNetConsoleValueProjection value)
    {
        var attribute = value.SourceKind ==
            DotNetConsoleBindingSourceKind.Argument
            ? string.Concat(
                "[global::Spectre.Console.Cli.CommandArgument(",
                value.ArgumentPosition.ToString(
                    System.Globalization.CultureInfo.InvariantCulture),
                ", ",
                DotNetSourceText.CSharpLiteral(value.AttributeTemplate),
                ")]")
            : string.Concat(
                "[global::Spectre.Console.Cli.CommandOption(",
                DotNetSourceText.CSharpLiteral(value.AttributeTemplate),
                ")]");
        DotNetConsoleRendering.Line(builder, 1, attribute);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "[global::System.ComponentModel.Description(",
                DotNetSourceText.CSharpLiteral(value.Summary),
                ")]"));
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "public ",
                value.PropertyType,
                " ",
                value.PropertyName,
                " { get; set; }"));
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "internal bool ",
                value.PropertyName,
                "Specified => ",
                SpecifiedExpression(value),
                ";"));
        DotNetConsoleRendering.Line(builder, 0);
    }

    private static string SpecifiedExpression(
        DotNetConsoleValueProjection value)
    {
        if (value.Repeated)
        {
            return string.Concat(
                value.PropertyName,
                " is { Length: > 0 }");
        }

        return value.Flag
            ? value.PropertyName
            : string.Concat(value.PropertyName, " is not null");
    }
}
