using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Binding;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleSettingsRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        projection.Commands
            .Select(command => new GeneratedOutput(
                Path(command, "Settings"),
                DotNetSourceText.Utf8(Render(command))))
            .ToImmutableArray();

    private static string Path(
        DotNetConsoleCommandProjection command,
        string suffix) =>
        string.Concat(
            "ProgramKitGenerated/Commands/",
            command.Symbol,
            "/",
            command.Symbol,
            suffix,
            ".cs");

    private static string Render(DotNetConsoleCommandProjection command)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Commands;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "internal sealed class ",
                command.SettingsTypeName,
                " : global::Spectre.Console.Cli.CommandSettings"));
        DotNetConsoleRendering.Line(builder, 0, "{");
        foreach (var value in command.Values.OrderBy(
                     static item => item.ConstructorPosition))
        {
            RenderValue(builder, value);
        }

        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static void RenderValue(
        StringBuilder builder,
        DotNetConsoleValueProjection value)
    {
        var backingField = string.Concat(
            char.ToLowerInvariant(value.PropertyName[0]),
            value.PropertyName[1..]);
        var attribute = value.SourceKind ==
            DotNetConsoleBindingSourceKind.Argument
            ? string.Concat(
                "[global::Spectre.Console.Cli.CommandArgument(",
                value.ArgumentPosition.ToString(
                    System.Globalization.CultureInfo.InvariantCulture),
                ", ",
                DotNetSourceText.CSharpLiteral(value.AttributeTemplate),
                ")]")
            : string.Concat(
                "[global::Spectre.Console.Cli.CommandOption(",
                DotNetSourceText.CSharpLiteral(value.AttributeTemplate),
                ")]");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat("private ", value.PropertyType, " ", backingField, ";"));
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(builder, 1, attribute);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "[global::System.ComponentModel.Description(",
                DotNetSourceText.CSharpLiteral(value.Summary),
                ")]"));
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat("public ", value.PropertyType, " ", value.PropertyName));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat("get => ", backingField, ";"));
        DotNetConsoleRendering.Line(builder, 2, "set");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            string.Concat(backingField, " = value;"));
        DotNetConsoleRendering.Line(
            builder,
            3,
            string.Concat(value.PropertyName, "Specified = true;"));
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "internal bool ",
                value.PropertyName,
                "Specified { get; private set; }"));
        DotNetConsoleRendering.Line(builder, 0);
    }
}
