using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleInvocationFailureRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder outcome = new();
        DotNetConsoleRendering.Line(outcome, 0, "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(outcome, 0, "#nullable enable");
        DotNetConsoleRendering.Line(outcome, 0);
        DotNetConsoleRendering.Line(outcome, 0, "namespace GeneratedHost.Hosting;");
        DotNetConsoleRendering.Line(outcome, 0);
        DotNetConsoleRendering.Line(
            outcome,
            0,
            "internal static class ProgramKitInvocationOutcome");
        DotNetConsoleRendering.Line(outcome, 0, "{");
        DotNetConsoleRendering.Line(
            outcome,
            1,
            "internal static async global::System.Threading.Tasks.Task<int> RunAsync(");
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "global::System.Func<global::System.Threading.Tasks.Task<int>> invocation,");
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "global::System.Threading.CancellationToken cancellationToken)");
        DotNetConsoleRendering.Line(outcome, 1, "{");
        DotNetConsoleRendering.Line(outcome, 2, "try");
        DotNetConsoleRendering.Line(outcome, 2, "{");
        DotNetConsoleRendering.Line(
            outcome,
            3,
            "return await invocation().ConfigureAwait(false);");
        DotNetConsoleRendering.Line(outcome, 2, "}");
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "catch (global::System.OperationCanceledException) when (cancellationToken.IsCancellationRequested)");
        DotNetConsoleRendering.Line(outcome, 2, "{");
        DotNetConsoleRendering.Line(
            outcome,
            3,
            string.Concat("return ", projection.CancellationExitCode, ";"));
        DotNetConsoleRendering.Line(outcome, 2, "}");
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "catch (global::Spectre.Console.Cli.CommandParseException exception)");
        RenderInvalid(outcome, projection.InvalidInvocationExitCode);
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "catch (global::Spectre.Console.Cli.CommandRuntimeException exception)");
        RenderInvalid(outcome, projection.InvalidInvocationExitCode);
        DotNetConsoleRendering.Line(
            outcome,
            2,
            "catch (global::System.Exception)");
        DotNetConsoleRendering.Line(outcome, 2, "{");
        DotNetConsoleRendering.Line(
            outcome,
            3,
            "global::System.Console.Error.WriteLine(\"Unexpected internal command failure.\");");
        DotNetConsoleRendering.Line(
            outcome,
            3,
            string.Concat("return ", projection.InternalFailureExitCode, ";"));
        DotNetConsoleRendering.Line(outcome, 2, "}");
        DotNetConsoleRendering.Line(outcome, 1, "}");
        DotNetConsoleRendering.Line(outcome, 0, "}");
        return
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Hosting/ProgramKitInvocationOutcome.cs",
                DotNetSourceText.Utf8(outcome.ToString())),
        ];
    }

    private static void RenderInvalid(
        StringBuilder builder,
        int exitCode)
    {
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "global::System.Console.Error.WriteLine(exception.Message);");
        DotNetConsoleRendering.Line(
            builder,
            3,
            string.Concat("return ", exitCode, ";"));
        DotNetConsoleRendering.Line(builder, 2, "}");
    }
}
