using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleServiceAuditRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Hosting/ProgramKitServiceRegistrationAudit.cs",
                DotNetSourceText.Utf8(RenderAudit(projection))),
        ];

    private static string RenderAudit(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Hosting;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "internal static class ProgramKitServiceRegistrationAudit");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "internal static void Audit(");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::System.ArgumentNullException.ThrowIfNull(services);");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "AuditFeature(services, typeof(",
                DotNetConsoleRendering.Type(projection.FeatureType),
                "));"));
        foreach (var command in projection.Commands.OrderBy(
                     static item => item.Symbol,
                     StringComparer.Ordinal))
        {
            DotNetConsoleRendering.Line(
                builder,
                2,
                string.Concat(
                    "AuditContract(services, typeof(",
                    DotNetConsoleRendering.Type(command.HandlerType),
                    "), required: true);"));
            if (command.ValidatorType is not null)
            {
                DotNetConsoleRendering.Line(
                    builder,
                    2,
                    string.Concat(
                        "AuditContract(services, typeof(",
                        DotNetConsoleRendering.Type(command.ValidatorType),
                        "), required: false);"));
            }
        }

        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0);
        RenderFeatureAudit(builder);
        DotNetConsoleRendering.Line(builder, 0);
        RenderContractAudit(builder);
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static void RenderFeatureAudit(StringBuilder builder)
    {
        DotNetConsoleRendering.Line(
            builder,
            1,
            "private static void AuditFeature(");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::System.Type featureType)");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "foreach (var descriptor in services)");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "var implementationType = descriptor.IsKeyedService");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "? descriptor.KeyedImplementationType");
        DotNetConsoleRendering.Line(
            builder,
            4,
            ": descriptor.ImplementationType;");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "if (descriptor.ServiceType == typeof(global::CShells.Features.IShellFeature) ||");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "descriptor.ServiceType == featureType ||");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "implementationType == featureType)");
        DotNetConsoleRendering.Line(builder, 3, "{");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "throw new global::System.InvalidOperationException(");
        DotNetConsoleRendering.Line(
            builder,
            5,
            "\"The generated Console host composes exactly one binding-selected feature; feature registrations are forbidden.\");");
        DotNetConsoleRendering.Line(builder, 3, "}");
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(builder, 1, "}");
    }

    private static void RenderContractAudit(StringBuilder builder)
    {
        DotNetConsoleRendering.Line(
            builder,
            1,
            "private static void AuditContract(");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::System.Type contractType,");
        DotNetConsoleRendering.Line(builder, 2, "bool required)");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "var matches = new global::System.Collections.Generic.List<global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor>();");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "foreach (var descriptor in services)");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "if (descriptor.ServiceType == contractType)");
        DotNetConsoleRendering.Line(builder, 3, "{");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "matches.Add(descriptor);");
        DotNetConsoleRendering.Line(builder, 3, "}");
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "var expected = required ? 1 : matches.Count;");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "if (matches.Count != expected || matches.Count > 1)");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "throw new global::System.InvalidOperationException(");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "\"Console handlers require exactly one registration and validators allow at most one registration.\");");
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "if (matches.Count == 0)");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(builder, 3, "return;");
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "var match = matches[0];");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "var implementationType = match.IsKeyedService");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "? match.KeyedImplementationType");
        DotNetConsoleRendering.Line(
            builder,
            3,
            ": match.ImplementationType;");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "if (match.IsKeyedService ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "match.Lifetime != global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "implementationType is null ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "implementationType.IsAbstract ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "implementationType.IsInterface ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "implementationType.ContainsGenericParameters ||");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "!contractType.IsAssignableFrom(implementationType))");
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "throw new global::System.InvalidOperationException(");
        DotNetConsoleRendering.Line(
            builder,
            4,
            "\"Console handler and validator registrations must be unkeyed scoped implementation types.\");");
        DotNetConsoleRendering.Line(builder, 2, "}");
        DotNetConsoleRendering.Line(builder, 1, "}");
    }
}
