using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleProgramRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Program.cs",
                DotNetSourceText.Utf8(RenderProgram(projection))),
        ];

    private static string RenderProgram(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "using Spectre.Console.Cli;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "var services = new global::Microsoft.Extensions.DependencyInjection.ServiceCollection();");
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "global::CShells.Features.IShellFeature feature = new ",
                DotNetConsoleRendering.Type(projection.FeatureType),
                "();"));
        DotNetConsoleRendering.Line(
            builder,
            0,
            "feature.ConfigureServices(services);");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "global::GeneratedHost.Hosting.ProgramKitServiceRegistrationAudit.Audit(services);");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "var registrar = new global::GeneratedHost.Hosting.ProgramKitTypeRegistrar(services);");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "var application = new global::Spectre.Console.Cli.CommandApp(registrar);");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "application.Configure(configuration =>");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "configuration.SetApplicationName(",
                DotNetSourceText.CSharpLiteral(projection.ApplicationName),
                ");"));
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "configuration.SetApplicationVersion(",
                DotNetSourceText.CSharpLiteral(projection.ApplicationVersion),
                ");"));
        DotNetConsoleRendering.Line(
            builder,
            1,
            "configuration.PropagateExceptions();");
        var counter = 0;
        foreach (var node in projection.CommandTrie)
        {
            RenderNode(builder, node, "configuration", 1, ref counter);
        }

        DotNetConsoleRendering.Line(builder, 0, "});");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "using var cancellation = new global::System.Threading.CancellationTokenSource();");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "global::System.ConsoleCancelEventHandler cancel = (_, eventArgs) =>");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "eventArgs.Cancel = true;");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "cancellation.Cancel();");
        DotNetConsoleRendering.Line(builder, 0, "};");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "global::System.Console.CancelKeyPress += cancel;");
        DotNetConsoleRendering.Line(builder, 0, "try");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "return await application.RunAsync(args, cancellation.Token);");
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0, "finally");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "global::System.Console.CancelKeyPress -= cancel;");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static void RenderNode(
        StringBuilder builder,
        DotNetConsoleCommandTrieNode node,
        string configurator,
        int indentation,
        ref int counter)
    {
        if (node.Children.IsDefaultOrEmpty)
        {
            var command = node.Command ??
                throw new InvalidOperationException(
                    "A leaf command trie node requires a command.");
            DotNetConsoleRendering.Line(
                builder,
                indentation,
                string.Concat(
                    configurator,
                    ".AddCommand<global::GeneratedHost.Commands.",
                    command.CommandTypeName,
                    ">(",
                    DotNetSourceText.CSharpLiteral(node.Token),
                    ").WithDescription(",
                    DotNetSourceText.CSharpLiteral(command.Summary),
                    ");"));
            return;
        }

        var branch = string.Concat(
            "branch",
            counter.ToString(
                System.Globalization.CultureInfo.InvariantCulture));
        counter++;
        DotNetConsoleRendering.Line(
            builder,
            indentation,
            string.Concat(
                configurator,
                ".AddBranch(",
                DotNetSourceText.CSharpLiteral(node.Token),
                ", ",
                branch,
                " =>"));
        DotNetConsoleRendering.Line(builder, indentation, "{");
        if (node.Command is not null)
        {
            DotNetConsoleRendering.Line(
                builder,
                indentation + 1,
                string.Concat(
                    branch,
                    ".SetDefaultCommand<global::GeneratedHost.Commands.",
                    node.Command.CommandTypeName,
                    ">();"));
        }

        foreach (var child in node.Children)
        {
            RenderNode(
                builder,
                child,
                branch,
                indentation + 1,
                ref counter);
        }

        DotNetConsoleRendering.Line(builder, indentation, "});");
    }
}
