using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleApplicationConfigurationRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Hosting/ProgramKitCommandConfiguration.cs",
                DotNetSourceText.Utf8(RenderSource(projection))),
        ];

    private static string RenderSource(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(builder, 0, "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(builder, 0, "using Spectre.Console.Cli;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(builder, 0, "namespace GeneratedHost.Hosting;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "internal static class ProgramKitCommandConfiguration");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "internal static void Configure(global::Spectre.Console.Cli.IConfigurator configuration)");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "configuration.SetApplicationName(",
                DotNetSourceText.CSharpLiteral(projection.ApplicationName),
                ");"));
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "configuration.SetApplicationVersion(",
                DotNetSourceText.CSharpLiteral(projection.ApplicationVersion),
                ");"));
        DotNetConsoleRendering.Line(
            builder,
            2,
            "configuration.SetApplicationCulture(global::System.Globalization.CultureInfo.InvariantCulture);");
        DotNetConsoleRendering.Line(builder, 2, "configuration.UseStrictParsing();");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "configuration.CaseSensitivity(global::Spectre.Console.Cli.CaseSensitivity.All);");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "configuration.CancellationExitCode(",
                projection.CancellationExitCode,
                ");"));
        DotNetConsoleRendering.Line(builder, 2, "configuration.PropagateExceptions();");
        var counter = 0;
        foreach (var node in projection.CommandTrie)
        {
            RenderNode(builder, node, "configuration", 2, ref counter);
        }

        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static void RenderNode(
        StringBuilder builder,
        DotNetConsoleCommandTrieNode node,
        string configurator,
        int indentation,
        ref int counter)
    {
        if (node.Children.IsDefaultOrEmpty)
        {
            var command = node.Command ??
                throw new InvalidOperationException(
                    "A leaf command trie node requires a command.");
            DotNetConsoleRendering.Line(
                builder,
                indentation,
                string.Concat(
                    configurator,
                    ".AddCommand<global::GeneratedHost.Commands.",
                    command.CommandTypeName,
                    ">(",
                    DotNetSourceText.CSharpLiteral(node.Token),
                    ").WithDescription(",
                    DotNetSourceText.CSharpLiteral(command.Summary),
                    ");"));
            return;
        }

        var branch = string.Concat(
            "branch",
            counter.ToString(
                System.Globalization.CultureInfo.InvariantCulture));
        counter++;
        DotNetConsoleRendering.Line(
            builder,
            indentation,
            string.Concat(
                configurator,
                ".AddBranch(",
                DotNetSourceText.CSharpLiteral(node.Token),
                ", ",
                branch,
                " =>"));
        DotNetConsoleRendering.Line(builder, indentation, "{");
        if (node.Command is not null)
        {
            DotNetConsoleRendering.Line(
                builder,
                indentation + 1,
                string.Concat(
                    branch,
                    ".SetDefaultCommand<global::GeneratedHost.Commands.",
                    node.Command.CommandTypeName,
                    ">();"));
        }

        foreach (var child in node.Children)
        {
            RenderNode(builder, child, branch, indentation + 1, ref counter);
        }

        DotNetConsoleRendering.Line(builder, indentation, "});");
    }
}
