using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleCommandRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        projection.Commands
            .Select(command => new GeneratedOutput(
                string.Concat(
                    "ProgramKitGenerated/Commands/",
                    command.Symbol,
                    "/",
                    command.Symbol,
                    "Command.cs"),
                DotNetSourceText.Utf8(Render(command))))
            .ToImmutableArray();

    private static string Render(DotNetConsoleCommandProjection command)
    {
        var handlerType = DotNetConsoleRendering.Type(command.HandlerType);
        var validatorType = command.ValidatorType is null
            ? null
            : DotNetConsoleRendering.Type(command.ValidatorType);
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Commands;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "internal sealed class ",
                command.CommandTypeName,
                " : global::Spectre.Console.Cli.AsyncCommand<",
                command.SettingsTypeName,
                ">"));
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "private readonly ",
                handlerType,
                " handler;"));
        DotNetConsoleRendering.Line(builder, 0);
        if (validatorType is not null)
        {
            DotNetConsoleRendering.Line(
                builder,
                1,
                string.Concat(
                    "private readonly ",
                    validatorType,
                    "? validator;"));
            DotNetConsoleRendering.Line(builder, 0);
        }

        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "public ",
                command.CommandTypeName,
                "(",
                handlerType,
                " handler",
                validatorType is null
                    ? ")"
                    : string.Concat(
                        ", ",
                        validatorType,
                        "? validator = null)")));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "this.handler = handler ?? throw new global::System.ArgumentNullException(nameof(handler));");
        if (validatorType is not null)
        {
            DotNetConsoleRendering.Line(
                builder,
                2,
                "this.validator = validator;");
        }

        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "protected override async global::System.Threading.Tasks.Task<int> ExecuteAsync(",
                "global::Spectre.Console.Cli.CommandContext context, ",
                command.SettingsTypeName,
                " settings, ",
                "global::System.Threading.CancellationToken cancellationToken)"));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "_ = context;");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "var request = ",
                command.RequestFactoryTypeName,
                ".Create(settings);"));
        if (validatorType is not null)
        {
            DotNetConsoleRendering.Line(
                builder,
                2,
                "if (validator is not null)");
            DotNetConsoleRendering.Line(builder, 2, "{");
            DotNetConsoleRendering.Line(
                builder,
                3,
                "var validation = await validator.ValidateAsync(request, cancellationToken).ConfigureAwait(false);");
            DotNetConsoleRendering.Line(
                builder,
                3,
                "if (!validation.IsValid)");
            DotNetConsoleRendering.Line(builder, 3, "{");
            DotNetConsoleRendering.Line(
                builder,
                4,
                "if (validation.Messages is null || validation.Messages.Count == 0)");
            DotNetConsoleRendering.Line(builder, 4, "{");
            DotNetConsoleRendering.Line(
                builder,
                5,
                "global::Spectre.Console.AnsiConsole.WriteLine(\"Consumer validation failed.\");");
            DotNetConsoleRendering.Line(builder, 4, "}");
            DotNetConsoleRendering.Line(builder, 4, "else");
            DotNetConsoleRendering.Line(builder, 4, "{");
            DotNetConsoleRendering.Line(
                builder,
                5,
                "foreach (var message in validation.Messages)");
            DotNetConsoleRendering.Line(builder, 5, "{");
            DotNetConsoleRendering.Line(
                builder,
                6,
                "global::Spectre.Console.AnsiConsole.WriteLine(message ?? string.Empty);");
            DotNetConsoleRendering.Line(builder, 5, "}");
            DotNetConsoleRendering.Line(builder, 4, "}");
            DotNetConsoleRendering.Line(
                builder,
                4,
                string.Concat(
                    "return ",
                    command.InvalidInvocationExitCode,
                    ";"));
            DotNetConsoleRendering.Line(builder, 3, "}");
            DotNetConsoleRendering.Line(builder, 2, "}");
        }

        DotNetConsoleRendering.Line(
            builder,
            2,
            "return await handler.HandleAsync(request, cancellationToken).ConfigureAwait(false);");
        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }
}
