using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleInformationRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Hosting/ProgramKitInformationProtocol.cs",
                DotNetSourceText.Utf8(RenderSource(projection))),
        ];

    private static string RenderSource(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(builder, 0, "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(builder, 0, "namespace GeneratedHost.Hosting;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "internal static class ProgramKitInformationProtocol");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "internal static bool IsHelp(string[] arguments) =>");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::System.Array.Exists(arguments, static argument =>");
        DotNetConsoleRendering.Line(
            builder,
            3,
            "argument is \"--help\" or \"-h\");");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            "internal static bool TryRunCompletion(string[] arguments, out int exitCode)");
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "if (arguments.Length != 1 || arguments[0] != ",
                DotNetSourceText.CSharpLiteral(projection.CompletionOption),
                ")"));
        DotNetConsoleRendering.Line(builder, 2, "{");
        DotNetConsoleRendering.Line(builder, 3, "exitCode = 0;");
        DotNetConsoleRendering.Line(builder, 3, "return false;");
        DotNetConsoleRendering.Line(builder, 2, "}");
        foreach (var candidate in projection.CompletionCandidates)
        {
            DotNetConsoleRendering.Line(
                builder,
                2,
                string.Concat(
                    "global::System.Console.Out.WriteLine(",
                    DotNetSourceText.CSharpLiteral(candidate),
                    ");"));
        }

        DotNetConsoleRendering.Line(builder, 2, "exitCode = 0;");
        DotNetConsoleRendering.Line(builder, 2, "return true;");
        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }
}
