using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleProgramRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Program.cs",
                DotNetSourceText.Utf8(RenderProgram(projection))),
        ];

    private static string RenderProgram(
        DotNetConsoleHostProjection projection)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(builder, 0, "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(builder, 0, "using Spectre.Console.Cli;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "if (global::GeneratedHost.Hosting.ProgramKitInformationProtocol.TryRunCompletion(args, out var completionExitCode))");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(builder, 1, "return completionExitCode;");
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "if (global::GeneratedHost.Hosting.ProgramKitInformationProtocol.IsHelp(args))");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "var informationApplication = new global::Spectre.Console.Cli.CommandApp();");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "informationApplication.Configure(global::GeneratedHost.Hosting.ProgramKitCommandConfiguration.Configure);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "return await global::GeneratedHost.Hosting.ProgramKitInvocationOutcome.RunAsync(");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "() => RunHelpAsync(informationApplication, args),");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "global::System.Threading.CancellationToken.None);");
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "static async global::System.Threading.Tasks.Task<int> RunHelpAsync(");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "global::Spectre.Console.Cli.CommandApp application,");
        DotNetConsoleRendering.Line(builder, 1, "string[] arguments)");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "_ = await application.RunAsync(arguments, global::System.Threading.CancellationToken.None).ConfigureAwait(false);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat("return ", projection.HelpExitCode, ";"));
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "using var cancellation = new global::System.Threading.CancellationTokenSource();");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "global::System.ConsoleCancelEventHandler cancel = (_, eventArgs) =>");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(builder, 1, "eventArgs.Cancel = true;");
        DotNetConsoleRendering.Line(builder, 1, "cancellation.Cancel();");
        DotNetConsoleRendering.Line(builder, 0, "};");
        DotNetConsoleRendering.Line(
            builder,
            0,
            "global::System.Console.CancelKeyPress += cancel;");
        DotNetConsoleRendering.Line(builder, 0, "try");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "return await global::GeneratedHost.Hosting.ProgramKitInvocationOutcome.RunAsync(");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "() => RunCommandAsync(args, cancellation.Token),");
        DotNetConsoleRendering.Line(builder, 2, "cancellation.Token);");
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0, "finally");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "global::System.Console.CancelKeyPress -= cancel;");
        DotNetConsoleRendering.Line(builder, 0, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "static async global::System.Threading.Tasks.Task<int> RunCommandAsync(");
        DotNetConsoleRendering.Line(builder, 1, "string[] arguments,");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "global::System.Threading.CancellationToken cancellationToken)");
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "var services = new global::Microsoft.Extensions.DependencyInjection.ServiceCollection();");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "global::CShells.Features.IShellFeature feature = new ",
                DotNetConsoleRendering.Type(projection.FeatureType),
                "();"));
        DotNetConsoleRendering.Line(builder, 1, "feature.ConfigureServices(services);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "global::GeneratedHost.Hosting.ProgramKitServiceRegistrationAudit.Audit(services);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "var registrar = new global::GeneratedHost.Hosting.ProgramKitTypeRegistrar(services);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "var application = new global::Spectre.Console.Cli.CommandApp(registrar);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "application.Configure(global::GeneratedHost.Hosting.ProgramKitCommandConfiguration.Configure);");
        DotNetConsoleRendering.Line(
            builder,
            1,
            "return await application.RunAsync(arguments, cancellationToken).ConfigureAwait(false);");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }
}
