using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleTypeRegistrarRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        [
            new GeneratedOutput(
                "ProgramKitGenerated/Hosting/ProgramKitTypeRegistrar.cs",
                DotNetSourceText.Utf8(Source)),
        ];

    private const string Source =
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal sealed class ProgramKitTypeRegistrar :
            global::Spectre.Console.Cli.ITypeRegistrar
        {
            private readonly global::Microsoft.Extensions.DependencyInjection.IServiceCollection services;

            internal ProgramKitTypeRegistrar(
                global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            {
                this.services = services ??
                    throw new global::System.ArgumentNullException(nameof(services));
            }

            public void Register(
                global::System.Type service,
                global::System.Type implementation)
            {
                global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(
                    services,
                    service,
                    implementation);
            }

            public void RegisterInstance(
                global::System.Type service,
                object implementation)
            {
                global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(
                    services,
                    service,
                    implementation);
            }

            public void RegisterLazy(
                global::System.Type service,
                global::System.Func<object> factory)
            {
                global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(
                    services,
                    service,
                    _ => factory());
            }

            public global::Spectre.Console.Cli.ITypeResolver Build()
            {
                var provider = global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(
                    services,
                    new global::Microsoft.Extensions.DependencyInjection.ServiceProviderOptions
                    {
                        ValidateOnBuild = true,
                        ValidateScopes = true,
                    });
                return new ProgramKitTypeResolver(provider);
            }
        }

        internal sealed class ProgramKitTypeResolver :
            global::Spectre.Console.Cli.ITypeResolver,
            global::System.IDisposable
        {
            private readonly global::System.IServiceProvider provider;

            internal ProgramKitTypeResolver(
                global::System.IServiceProvider provider)
            {
                this.provider = provider ??
                    throw new global::System.ArgumentNullException(nameof(provider));
            }

            public object? Resolve(global::System.Type? type)
            {
                return type is null ? null : provider.GetService(type);
            }

            public void Dispose()
            {
                if (provider is global::System.IDisposable disposable)
                {
                    disposable.Dispose();
                }
            }
        }
        """;
}
