using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleCommandRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        projection.Commands
            .Select(command => new GeneratedOutput(
                string.Concat(
                    "ProgramKitGenerated/Commands/",
                    command.Symbol,
                    "/",
                    command.Symbol,
                    "Command.cs"),
                DotNetSourceText.Utf8(Render(command))))
            .ToImmutableArray();

    private static string Render(DotNetConsoleCommandProjection command)
    {
        var handlerType = DotNetConsoleRendering.Type(command.HandlerType);
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Commands;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "internal sealed class ",
                command.CommandTypeName,
                " : global::Spectre.Console.Cli.AsyncCommand<",
                command.SettingsTypeName,
                ">"));
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "private readonly ",
                handlerType,
                " handler;"));
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "public ",
                command.CommandTypeName,
                "(",
                handlerType,
                " handler)"));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "this.handler = handler ?? throw new global::System.ArgumentNullException(nameof(handler));");
        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "protected override async global::System.Threading.Tasks.Task<int> ExecuteAsync(",
                "global::Spectre.Console.Cli.CommandContext context, ",
                command.SettingsTypeName,
                " settings, ",
                "global::System.Threading.CancellationToken cancellationToken)"));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            "_ = context;");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "var request = ",
                command.RequestFactoryTypeName,
                ".Create(settings);"));
        DotNetConsoleRendering.Line(
            builder,
            2,
            "return await handler.HandleAsync(request, cancellationToken).ConfigureAwait(false);");
        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }
}
