using System.Text;
using Orbyss.ProgramKit.DotNet.Generation.Console.Binding;
using Orbyss.ProgramKit.DotNet.Generation.Console.Projection;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.Console.Rendering;

internal sealed class DotNetConsoleRequestFactoryRenderer :
    IDotNetConsoleOutputRenderer
{
    public ImmutableArray<GeneratedOutput> Render(
        DotNetConsoleHostProjection projection) =>
        projection.Commands
            .Select(command => new GeneratedOutput(
                string.Concat(
                    "ProgramKitGenerated/Commands/",
                    command.Symbol,
                    "/",
                    command.Symbol,
                    "RequestFactory.cs"),
                DotNetSourceText.Utf8(Render(command))))
            .ToImmutableArray();

    private static string Render(DotNetConsoleCommandProjection command)
    {
        StringBuilder builder = new();
        DotNetConsoleRendering.Line(
            builder,
            0,
            "// <auto-generated program-kit>");
        DotNetConsoleRendering.Line(builder, 0, "#nullable enable");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            "namespace GeneratedHost.Commands;");
        DotNetConsoleRendering.Line(builder, 0);
        DotNetConsoleRendering.Line(
            builder,
            0,
            string.Concat(
                "internal static class ",
                command.RequestFactoryTypeName));
        DotNetConsoleRendering.Line(builder, 0, "{");
        DotNetConsoleRendering.Line(
            builder,
            1,
            string.Concat(
                "internal static ",
                DotNetConsoleRendering.Type(command.RequestType),
                " Create(",
                command.SettingsTypeName,
                " settings)"));
        DotNetConsoleRendering.Line(builder, 1, "{");
        DotNetConsoleRendering.Line(
            builder,
            2,
            string.Concat(
                "return new ",
                DotNetConsoleRendering.Type(command.RequestType),
                "("));
        var ordered = command.Values
            .OrderBy(static value => value.ConstructorPosition)
            .ToArray();
        for (var index = 0; index < ordered.Length; index++)
        {
            DotNetConsoleRendering.Line(
                builder,
                3,
                string.Concat(
                    Expression(ordered[index]),
                    index == ordered.Length - 1 ? ");" : ","));
        }

        DotNetConsoleRendering.Line(builder, 1, "}");
        DotNetConsoleRendering.Line(builder, 0, "}");
        return builder.ToString();
    }

    private static string Expression(DotNetConsoleValueProjection value)
    {
        var access = string.Concat("settings.", value.PropertyName);
        if (value.Repeated)
        {
            var converted = string.Concat(
                "global::System.Collections.Immutable.ImmutableArray.CreateRange(",
                access,
                " ?? [])");
            return value.DefaultDisposition.Kind ==
                DotNetConsoleDefaultKind.Canonical
                ? string.Concat(
                    access,
                    " is null ? global::System.Collections.Immutable.ImmutableArray.Create(",
                    DotNetConsoleRendering.DefaultValue(value),
                    ") : ",
                    converted)
                : converted;
        }

        if (value.DefaultDisposition.Kind ==
            DotNetConsoleDefaultKind.Canonical)
        {
            return value.Flag
                ? access
                : string.Concat(
                    access,
                    " ?? ",
                    DotNetConsoleRendering.DefaultValue(value));
        }

        if (value.Flag ||
            value.RequestType.ReferenceNullability ==
                DotNetConsoleReferenceNullability.Nullable ||
            value.RequestType.MetadataName == "System.Nullable`1")
        {
            return access;
        }

        return value.ElementType == "global::System.String"
            ? string.Concat(access, "!")
            : string.Concat(access, ".GetValueOrDefault()");
    }
}
