using System.Collections.Immutable;

namespace Orbyss.ProgramKit.Artifacts.Versioning;

/// <summary>The semantic relationship represented by a version-map edge.</summary>
public enum VersionDependencyKind
{
    /// <summary>The source implements the target contract.</summary>
    Implements,

    /// <summary>The source reads the target representation.</summary>
    Reads,

    /// <summary>The source writes the target representation.</summary>
    Writes,

    /// <summary>The source validates the target.</summary>
    Validates,

    /// <summary>The source uses the target contract.</summary>
    UsesContract,

    /// <summary>The source is the wire schema of the target.</summary>
    WireSchemaOf,

    /// <summary>The source serializes with the target profile.</summary>
    SerializesWith,

    /// <summary>The source contributes a converter to the target profile.</summary>
    ContributesConverter,

    /// <summary>The source canonicalizes with the target profile.</summary>
    CanonicalizesWith,

    /// <summary>The source publicly exposes the target.</summary>
    PubliclyExposes,

    /// <summary>The source package depends on the target package.</summary>
    PackageDependsOn,

    /// <summary>The source is configured by the target.</summary>
    ConfiguredBy,

    /// <summary>The source is generated by the target.</summary>
    GeneratedBy,

    /// <summary>The source projects the target.</summary>
    Projects,

    /// <summary>The source composes the target.</summary>
    Composes,

    /// <summary>The source handles the target task definition.</summary>
    HandlesTask,

    /// <summary>The source schedules the target task definition.</summary>
    Schedules,

    /// <summary>The source migrates the target.</summary>
    Migrates,

    /// <summary>The source verifies the target.</summary>
    Verifies,
}
