// <auto-generated program-kit>
#nullable enable
using Microsoft.Playwright;

namespace GeneratedPublicBrowser.Operations;

internal static class OperatorAssistedPublicBrowserAcceptance
{
    internal static async Task RunOptInAsync(
        Uri publicBrowserBaseUri,
        Func<CancellationToken, Task> waitForHumanControlledCallback,
        CancellationToken cancellationToken)
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
        await using var context = await browser.NewContextAsync();
        var page = await context.NewPageAsync();
        await page.GotoAsync(new Uri(publicBrowserBaseUri, "authentication/login").AbsoluteUri);
        await waitForHumanControlledCallback(cancellationToken);
        await page.WaitForURLAsync("https://browser.example.test/authentication/login-callback");
        await context.ClearCookiesAsync();
    }
}
