// <auto-generated program-kit>
#nullable enable
using Microsoft.Playwright;

namespace GeneratedPublicBrowser.Operations;

internal static class PublicBrowserPlaywrightHarness
{
    internal static async Task VerifyAsync(
        string browserName,
        Uri publicBrowserBaseUri,
        Func<IPage, CancellationToken, Task> performLocalProviderLogin,
        Func<IPage, CancellationToken, Task> assertProtectedApiAccess,
        Func<IPage, CancellationToken, Task> assertAdversarialFailures,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        using var playwright = await Playwright.CreateAsync();
        var browserType = browserName switch
        {
            "chromium" => playwright.Chromium,
            "firefox" => playwright.Firefox,
            "webkit" => playwright.Webkit,
            _ => throw new ArgumentOutOfRangeException(nameof(browserName)),
        };
        await using var browser = await browserType.LaunchAsync(new() { Headless = true });
        await using var context = await browser.NewContextAsync(new()
        {
            BaseURL = publicBrowserBaseUri.AbsoluteUri,
            RecordHarPath = null,
            RecordVideoDir = null,
        });
        var page = await context.NewPageAsync();
        page.Request += (_, request) =>
        {
            if (request.Url.Contains("access_token=", StringComparison.OrdinalIgnoreCase) ||
                request.Url.Contains("id_token=", StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("A token entered a browser URL.");
        };
        await page.GotoAsync(publicBrowserBaseUri.AbsoluteUri);
        await performLocalProviderLogin(page, cancellationToken);
        await assertProtectedApiAccess(page, cancellationToken);
        await assertAdversarialFailures(page, cancellationToken);
        var localStorageCount = await page.EvaluateAsync<int>("() => window.localStorage.length");
        if (localStorageCount != 0)
            throw new InvalidOperationException("Authentication material entered durable local storage.");
        await page.GotoAsync(new Uri(publicBrowserBaseUri, "authentication/logout").AbsoluteUri);
        await context.ClearCookiesAsync();
    }
}
