// <auto-generated program-kit>
#nullable enable
using System.Security.Cryptography;
using System.Text;

namespace GeneratedPublicBrowser.Operations;

internal static class PublicBrowserProtocolVectors
{
    internal static readonly Uri Authority = new("https://identity.example.test/");
    internal static readonly Uri RedirectUri = new("https://browser.example.test/authentication/login-callback");
    internal static readonly Uri PostLogoutRedirectUri = new("https://browser.example.test/authentication/logout-callback");
    internal static readonly Uri ApiResource = new("https://api.example.test/");
    internal static readonly Uri ExpectedIssuer = new("https://identity.example.test/");
    internal const bool RefreshTokenExpected = false;

    internal static string CreateS256Challenge(string verifier)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(verifier);
        return Convert.ToBase64String(SHA256.HashData(Encoding.ASCII.GetBytes(verifier)))
            .TrimEnd('=').Replace('+', '-').Replace('/', '_');
    }

    internal static bool IsSafeCallback(Uri callback) =>
        callback == RedirectUri &&
        callback.Query.Length == 0 &&
        callback.Fragment.Length == 0;

    internal static bool IsSafeLogoutCallback(Uri callback) =>
        callback == PostLogoutRedirectUri &&
        callback.Query.Length == 0 &&
        callback.Fragment.Length == 0;

    internal static bool IsSafeAuthorizationResponse(
        Uri callback,
        Uri issuer,
        string expectedState,
        string actualState,
        string expectedNonce,
        string actualNonce) =>
        IsSafeCallback(callback) &&
        issuer == ExpectedIssuer &&
        !string.IsNullOrEmpty(expectedState) &&
        string.Equals(expectedState, actualState, StringComparison.Ordinal) &&
        !string.IsNullOrEmpty(expectedNonce) &&
        string.Equals(expectedNonce, actualNonce, StringComparison.Ordinal);

    internal static bool IsAllowedApiTarget(Uri target) =>
        string.Equals(
            target.GetLeftPart(UriPartial.Authority),
            ApiResource.GetLeftPart(UriPartial.Authority),
            StringComparison.Ordinal) &&
        target.AbsolutePath.StartsWith(ApiResource.AbsolutePath, StringComparison.Ordinal);

    internal static bool IsAccessTokenKind(string tokenType, string? jwtType) =>
        string.Equals(tokenType, "Bearer", StringComparison.Ordinal) &&
        string.Equals(jwtType, "at+jwt", StringComparison.Ordinal);
}
