// <auto-generated program-kit>
#nullable enable

namespace GeneratedHost.Hosting;

internal interface IProgramKitOidcClientAssertionProvider
{
    ValueTask<ProgramKitOidcClientAssertion> CreateAsync(
        string referenceIdentity,
        CancellationToken cancellationToken);
}
