// <auto-generated program-kit>
#nullable enable

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Routing.Template;
using Microsoft.Extensions.DependencyInjection;

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitOperationAuthorizationMiddleware : IMiddleware
{
    public async Task InvokeAsync(
        HttpContext context,
        RequestDelegate next)
    {
        var authorization = context.RequestServices
            .GetRequiredService<IAuthorizationService>();
        if (HttpMethods.IsGet(context.Request.Method) &&
            Match("/anonymous", context.Request.Path))
        {
            await next(context);
            return;
        }

        if (HttpMethods.IsGet(context.Request.Method) &&
            Match("/protected", context.Request.Path))
        {
            await AuthorizeAsync(
                context,
                authorization,
                next,
                "ProgramKit.AuthenticatedTransport");
            return;
        }

        if (HttpMethods.IsGet(context.Request.Method) &&
            Match("/denied", context.Request.Path))
        {
            await AuthorizeAsync(
                context,
                authorization,
                next,
                "Fixture.Denied");
            return;
        }

        await next(context);
    }

    private async Task AuthorizeAsync(
        HttpContext context,
        IAuthorizationService authorization,
        RequestDelegate next,
        string policy)
    {
        var result = await authorization.AuthorizeAsync(
            context.User,
            context,
            policy);
        if (result.Succeeded)
        {
            await next(context);
            return;
        }

        if (context.User.Identity?.IsAuthenticated == true)
        {
            await context.ForbidAsync("fixture");
        }
        else
        {
            await context.ChallengeAsync("fixture");
        }
    }

    private static bool Match(string template, PathString path)
    {
        var matcher = new TemplateMatcher(
            TemplateParser.Parse(template),
            new RouteValueDictionary());
        return matcher.TryMatch(path, new RouteValueDictionary());
    }
}
