// <auto-generated program-kit>
#nullable enable
using System.Diagnostics;
using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;

namespace GeneratedHost.Hosting;

internal static partial class ProgramKitTransportFailureDiagnostics
{
    internal const string MeterName = "Orbyss.ProgramKit.TransportFailures";
    private static readonly Meter Meter = new(MeterName, "1.0.0");
    private static readonly Counter<long> Outcomes = Meter.CreateCounter<long>(
        "program_kit.transport.failure.outcomes",
        "{outcome}",
        "Sanitized handled transport-failure outcomes.");

    [LoggerMessage(
        EventId = 19001,
        EventName = "TransportFailureHandled",
        Level = LogLevel.Warning,
        Message = "Transport failure {FailureIdentity} produced status {StatusCode} with outcome {Outcome}.")]
    private static partial void WriteHandled(
        ILogger logger,
        string failureIdentity,
        int statusCode,
        string outcome);

    internal static void Record(
        ILogger logger,
        string failureIdentity,
        int statusCode,
        string outcome)
    {
        WriteHandled(logger, failureIdentity, statusCode, outcome);
        Outcomes.Add(
            1,
            new KeyValuePair<string, object?>("failure.identity", failureIdentity),
            new KeyValuePair<string, object?>("http.response.status_code", statusCode),
            new KeyValuePair<string, object?>("outcome", outcome));
        Activity.Current?.SetTag(
            "program_kit.failure.identity",
            failureIdentity);
        Activity.Current?.SetStatus(ActivityStatusCode.Error);
    }
}
