// <auto-generated program-kit>
#nullable enable
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitMappedTransportFailureHandler : IExceptionHandler
{
    private readonly IProblemDetailsService _service;
    private readonly IHostEnvironment _environment;
    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;

    public ProgramKitMappedTransportFailureHandler(
        IProblemDetailsService service,
        IHostEnvironment environment,
        ILogger<ProgramKitTransportFailureCategory> logger)
    {
        _service = service;
        _environment = environment;
        _logger = logger;
    }

    public ValueTask<bool> TryHandleAsync(
        HttpContext context,
        Exception exception,
        CancellationToken cancellationToken)
    {
        if (context.Response.HasStarted ||
            exception is OperationCanceledException)
        {
            return ValueTask.FromResult(false);
        }

        if (exception is InvalidOperationException)
        {
            return ProgramKitProblemDetailsWriter.WriteAsync(
                context,
                _service,
                _environment,
                _logger,
                "pkid:failure:transport:conflict",
                409,
                "https://errors.orbyss.test/conflict",
                "Conflict",
                "The request conflicts with the current state.",
                "The declared operation conflict occurred.");
        }

        return ValueTask.FromResult(false);
    }
}
