// <auto-generated program-kit>
#nullable enable
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitFallbackTransportFailureHandler : IExceptionHandler
{
    private readonly IProblemDetailsService _service;
    private readonly IHostEnvironment _environment;
    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;

    public ProgramKitFallbackTransportFailureHandler(
        IProblemDetailsService service,
        IHostEnvironment environment,
        ILogger<ProgramKitTransportFailureCategory> logger)
    {
        _service = service;
        _environment = environment;
        _logger = logger;
    }

    public ValueTask<bool> TryHandleAsync(
        HttpContext context,
        Exception exception,
        CancellationToken cancellationToken)
    {
        if (context.Response.HasStarted ||
            exception is OperationCanceledException)
        {
            return ValueTask.FromResult(false);
        }

        return ProgramKitProblemDetailsWriter.WriteAsync(
            context,
            _service,
            _environment,
            _logger,
            "pkid:failure:transport:internal",
            500,
            "https://errors.orbyss.test/internal",
            "Unexpected failure",
            "The request could not be completed.",
            "The request failed in the local development host.");
    }
}
