// <auto-generated program-kit>
#nullable enable
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace GeneratedHost.Hosting;

internal static class ProgramKitProblemDetailsWriter
{
    internal static async ValueTask<bool> WriteAsync(
        HttpContext context,
        IProblemDetailsService service,
        IHostEnvironment environment,
        ILogger logger,
        string identity,
        int statusCode,
        string type,
        string title,
        string productionDetail,
        string developmentDetail)
    {
        if (context.Response.HasStarted)
        {
            return false;
        }

        context.Response.StatusCode = statusCode;
        var problem = new ProblemDetails
        {
            Status = statusCode,
            Type = type,
            Title = title,
            Detail = environment.IsDevelopment()
                ? developmentDetail
                : productionDetail,
            Instance = context.Request.Path,
        };
        _ = await service.TryWriteAsync(new ProblemDetailsContext
        {
            HttpContext = context,
            ProblemDetails = problem,
        });
        ProgramKitTransportFailureDiagnostics.Record(
            logger,
            identity,
            statusCode,
            "handled");
        return true;
    }
}
