// <auto-generated program-kit>
#nullable enable
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace GeneratedHost.Hosting;

internal sealed class ProgramKitClientDisconnectExceptionHandler :
    IExceptionHandler
{
    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;

    public ProgramKitClientDisconnectExceptionHandler(
        ILogger<ProgramKitTransportFailureCategory> logger)
    {
        _logger = logger;
    }

    public ValueTask<bool> TryHandleAsync(
        HttpContext context,
        Exception exception,
        CancellationToken cancellationToken)
    {
        if (exception is not OperationCanceledException ||
            !context.RequestAborted.IsCancellationRequested)
        {
            return ValueTask.FromResult(false);
        }

        ProgramKitTransportFailureDiagnostics.Record(
            _logger,
            "pkid:failure:transport:client-disconnect",
            0,
            "client-disconnect");
        context.Abort();
        return ValueTask.FromResult(true);
    }
}
