<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <None Include="../schema.sql" Link="schema.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
