using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Engine.Semantics.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class EngineSemanticsAnalyzersParticipationReceiptGenerator :
    IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.AnalyzerConfigOptionsProvider,
            static (productionContext, optionsProvider) =>
            {
                if (!optionsProvider.GlobalOptions.TryGetValue(
                        "build_property.ProgramKitCompilerInvocationNonce",
                        out var nonce) ||
                    nonce.Length != 32 ||
                    nonce.Any(character => !Uri.IsHexDigit(character)))
                {
                    return;
                }

                productionContext.AddSource(
                    "Engine.Semantics.AnalyzersParticipationReceipt.g.cs",
                    SourceText.From(
                        string.Concat(
                            "// <auto-generated/>\n",
                            "// PKCG participation-receipt analyzer=",
                            "Engine.Semantics.Analyzers",
                            "\n"),
                        Encoding.UTF8));
            });
    }
}
