using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Engine.Semantics.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class EngineSemanticsAnalyzersParticipationReceiptGenerator :
    IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.AnalyzerConfigOptionsProvider,
            static (productionContext, optionsProvider) =>
            {
                if (!optionsProvider.GlobalOptions.TryGetValue(
                        "build_property.ProgramKitCompilerInvocationNonce",
                        out var nonce) ||
                    nonce.Length != 32 ||
                    nonce.Any(character => !Uri.IsHexDigit(character)))
                {
                    return;
                }

                _ = optionsProvider.GlobalOptions.TryGetValue(
                    "build_property.MSBuildProjectName",
                    out var project);
                _ = optionsProvider.GlobalOptions.TryGetValue(
                    "build_property.ProgramKitCSharpGateVerificationProfile",
                    out var profile);
                productionContext.AddSource(
                    "Engine.Semantics.AnalyzersParticipationReceipt." +
                    nonce.ToLowerInvariant() +
                    ".g.cs",
                    SourceText.From(
                        string.Concat(
                            "// <auto-generated/>\n",
                            "// PKCG participation-receipt analyzer=",
                            "Engine.Semantics.Analyzers nonce=",
                            nonce.ToLowerInvariant(),
                            " project=",
                            project ?? string.Empty,
                            " profile=",
                            profile ?? string.Empty,
                            "\n"),
                        Encoding.UTF8));
            });
    }
}
