using System.Globalization;
using System.Text;
using Orbyss.ProgramKit.DotNet.Operations.Security;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation;

internal static class DotNetOAuthServiceClientProjectionRenderer
{
    internal static ImmutableArray<GeneratedOutput> Render(
        DotNetSecurityConfiguration security)
    {
        if (security.OAuthClientCredentials.IsDefaultOrEmpty &&
            security.OAuthTokenExchanges.IsDefaultOrEmpty)
        {
            return [];
        }

        return
        [
            Output("ProgramKitOAuthGrantKind", RenderGrantKind()),
            Output("ProgramKitOAuthTokenKind", RenderTokenKind()),
            Output("ProgramKitOAuthTokenSourceValue", RenderTokenSourceValue()),
            Output("ProgramKitOAuthAccessToken", RenderAccessToken()),
            Output("IProgramKitOAuthTokenSource", RenderTokenSource()),
            Output("IProgramKitOAuthClientCredentialProvider", RenderCredentialProvider()),
            Output("IProgramKitOAuthClientAssertionProvider", RenderClientAssertionProvider()),
            Output("ProgramKitOAuthProfile", RenderProfile()),
            Output("ProgramKitOAuthTokenResponse", RenderTokenResponse()),
            Output("ProgramKitOAuthProfileCatalog", RenderCatalog(security)),
            Output("ProgramKitOAuthTokenEndpointClient", RenderClient()),
            Output("ProgramKitOAuthBearerHandler", RenderHandler()),
        ];
    }

    internal static string RenderRegistration(DotNetSecurityConfiguration security)
    {
        if (security.OAuthClientCredentials.IsDefaultOrEmpty &&
            security.OAuthTokenExchanges.IsDefaultOrEmpty)
        {
            return string.Empty;
        }

        var builder = new StringBuilder();
        builder.AppendLine("builder.Services.AddMemoryCache();");
        builder.AppendLine("builder.Services.AddSingleton<global::GeneratedHost.Hosting.ProgramKitOAuthTokenEndpointClient>();");
        foreach (var profile in security.OAuthClientCredentials
                     .Select(static item => (item.ClientName, item.RequestTimeoutSeconds))
                     .Concat(security.OAuthTokenExchanges.Select(static item =>
                         (item.ClientName, item.RequestTimeoutSeconds)))
                     .OrderBy(static item => item.ClientName, StringComparer.Ordinal))
        {
            builder.Append("builder.Services.AddHttpClient(")
                .Append(Literal(string.Concat("ProgramKit.OAuth.", profile.ClientName)))
                .Append(", client => client.Timeout = global::System.TimeSpan.FromSeconds(")
                .Append(profile.RequestTimeoutSeconds.ToString(CultureInfo.InvariantCulture))
                .AppendLine("));");
        }

        return builder.ToString();
    }

    private static string RenderGrantKind() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal enum ProgramKitOAuthGrantKind
        {
            ClientCredentials,
            TokenExchangeRfc8693,
        }
        """;

    private static string RenderTokenKind() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal enum ProgramKitOAuthTokenKind
        {
            AccessToken,
            Jwt,
        }
        """;

    private static string RenderTokenSourceValue() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal sealed record ProgramKitOAuthTokenSourceValue(
            string Value,
            ProgramKitOAuthTokenKind TokenKind,
            string ProvenanceIdentity);
        """;

    private static string RenderAccessToken() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal sealed record ProgramKitOAuthAccessToken(
            string Value,
            ProgramKitOAuthTokenKind TokenKind,
            DateTimeOffset ExpiresAt);
        """;

    private static string RenderTokenSource() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal interface IProgramKitOAuthTokenSource
        {
            ValueTask<ProgramKitOAuthTokenSourceValue> GetAsync(
                string sourceIdentity,
                CancellationToken cancellationToken);
        }
        """;

    private static string RenderCredentialProvider() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal interface IProgramKitOAuthClientCredentialProvider
        {
            ValueTask<string> GetAsync(
                string referenceIdentity,
                CancellationToken cancellationToken);
        }
        """;

    private static string RenderClientAssertionProvider() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal interface IProgramKitOAuthClientAssertionProvider
        {
            ValueTask<string> CreateAsync(
                string referenceIdentity,
                Uri tokenEndpoint,
                CancellationToken cancellationToken);
        }
        """;

    private static string RenderProfile() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        internal sealed record ProgramKitOAuthProfile(
            string ClientName,
            ProgramKitOAuthGrantKind GrantKind,
            Uri TokenEndpoint,
            string ClientId,
            string AuthenticationMethod,
            string AuthenticationReferenceIdentity,
            string? AuthenticationConfigurationKey,
            Uri Resource,
            string Audience,
            string Scope,
            ProgramKitOAuthTokenKind RequestedTokenKind,
            ProgramKitOAuthTokenKind ExpectedIssuedTokenKind,
            string? SubjectSourceIdentity,
            ProgramKitOAuthTokenKind? SubjectTokenKind,
            string? ActorSourceIdentity,
            ProgramKitOAuthTokenKind? ActorTokenKind,
            string? ExchangeMode,
            int RequestedLifetimeSeconds,
            bool CacheEnabled,
            int ExpirySkewSeconds,
            int MaximumCacheLifetimeSeconds);
        """;

    private static string RenderTokenResponse() =>
        """
        // <auto-generated program-kit>
        #nullable enable
        using System.Text.Json.Serialization;

        namespace GeneratedHost.Hosting;

        internal sealed record ProgramKitOAuthTokenResponse(
            [property: JsonPropertyName("access_token")] string? AccessToken,
            [property: JsonPropertyName("issued_token_type")] string? IssuedTokenType,
            [property: JsonPropertyName("token_type")] string? TokenType,
            [property: JsonPropertyName("expires_in")] int ExpiresIn,
            [property: JsonPropertyName("scope")] string? Scope);
        """;

    private static string RenderCatalog(DotNetSecurityConfiguration security)
    {
        var builder = Source();
        builder.AppendLine("internal static class ProgramKitOAuthProfileCatalog");
        builder.AppendLine("{");
        builder.AppendLine("    internal static ProgramKitOAuthProfile Resolve(string clientName) => clientName switch");
        builder.AppendLine("    {");
        foreach (var profile in security.OAuthClientCredentials
                     .OrderBy(static item => item.ClientName, StringComparer.Ordinal))
        {
            builder.Append("        ").Append(Literal(profile.ClientName)).Append(" => new(")
                .Append(Literal(profile.ClientName)).Append(", ProgramKitOAuthGrantKind.ClientCredentials, new Uri(")
                .Append(Literal(profile.TokenEndpoint.AbsoluteUri)).Append("), ")
                .Append(Literal(profile.ClientId)).Append(", ")
                .Append(Literal(Authentication(profile.Authentication.Method))).Append(", ")
                .Append(Literal(profile.Authentication.Reference.Identity.Value)).Append(", ")
                .Append(NullableLiteral(profile.Authentication.ConfigurationKey)).Append(", new Uri(")
                .Append(Literal(profile.Resource.AbsoluteUri)).Append("), ")
                .Append(Literal(profile.Audience)).Append(", ")
                .Append(Literal(Scope(profile.Scopes))).Append(", ProgramKitOAuthTokenKind.")
                .Append(TokenKind(profile.ExpectedIssuedTokenType)).Append(", ProgramKitOAuthTokenKind.")
                .Append(TokenKind(profile.ExpectedIssuedTokenType))
                .Append(", null, null, null, null, null, ")
                .Append(profile.RequestedLifetimeSeconds).Append(", true, ")
                .Append(profile.Cache.ExpirySkewSeconds).Append(", ")
                .Append(profile.Cache.MaximumLifetimeSeconds).AppendLine("),");
        }

        foreach (var profile in security.OAuthTokenExchanges
                     .OrderBy(static item => item.ClientName, StringComparer.Ordinal))
        {
            builder.Append("        ").Append(Literal(profile.ClientName)).Append(" => new(")
                .Append(Literal(profile.ClientName)).Append(", ProgramKitOAuthGrantKind.TokenExchangeRfc8693, new Uri(")
                .Append(Literal(profile.TokenEndpoint.AbsoluteUri)).Append("), ")
                .Append(Literal(profile.ClientId)).Append(", ")
                .Append(Literal(Authentication(profile.Authentication.Method))).Append(", ")
                .Append(Literal(profile.Authentication.Reference.Identity.Value)).Append(", ")
                .Append(NullableLiteral(profile.Authentication.ConfigurationKey)).Append(", new Uri(")
                .Append(Literal(profile.Resource.AbsoluteUri)).Append("), ")
                .Append(Literal(profile.Audience)).Append(", ")
                .Append(Literal(Scope(profile.Scopes))).Append(", ProgramKitOAuthTokenKind.")
                .Append(TokenKind(profile.RequestedTokenType)).Append(", ProgramKitOAuthTokenKind.")
                .Append(TokenKind(profile.ExpectedIssuedTokenType)).Append(", ")
                .Append(Literal(profile.SubjectToken.SourceIdentity.Value)).Append(", ProgramKitOAuthTokenKind.")
                .Append(TokenKind(profile.SubjectToken.TokenType)).Append(", ")
                .Append(profile.ActorToken is null ? "null, null, " : string.Concat(
                    Literal(profile.ActorToken.SourceIdentity.Value),
                    ", ProgramKitOAuthTokenKind.",
                    TokenKind(profile.ActorToken.TokenType),
                    ", "))
                .Append(Literal(profile.ExchangeMode.ToString())).Append(", ")
                .Append(profile.RequestedLifetimeSeconds).Append(", true, ")
                .Append(profile.Cache.ExpirySkewSeconds).Append(", ")
                .Append(profile.Cache.MaximumLifetimeSeconds).AppendLine("),");
        }

        builder.AppendLine("        _ => throw new InvalidOperationException(\"Unknown generated OAuth client profile.\"),");
        builder.AppendLine("    };");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderClient() =>
        """
        // <auto-generated program-kit>
        #nullable enable
        using System.Diagnostics;
        using System.Diagnostics.Metrics;
        using System.Globalization;
        using System.Net.Http.Headers;
        using System.Net.Http.Json;
        using System.Security.Cryptography;
        using System.Text;
        using Microsoft.Extensions.Caching.Memory;
        using Microsoft.Extensions.Configuration;

        namespace GeneratedHost.Hosting;

        internal sealed class ProgramKitOAuthTokenEndpointClient(
            IHttpClientFactory httpClientFactory,
            IMemoryCache cache,
            IConfiguration configuration,
            IProgramKitOAuthClientCredentialProvider credentialProvider,
            IProgramKitOAuthClientAssertionProvider assertionProvider,
            IProgramKitOAuthTokenSource tokenSource)
        {
            private static readonly ActivitySource Activities = new("GeneratedHost.OAuth");
            private static readonly Meter Meter = new("GeneratedHost.OAuth");
            private static readonly Counter<long> Requests = Meter.CreateCounter<long>("oauth.token.requests");

            internal async ValueTask<ProgramKitOAuthAccessToken> GetAsync(
                string clientName,
                CancellationToken cancellationToken)
            {
                cancellationToken.ThrowIfCancellationRequested();
                var profile = ProgramKitOAuthProfileCatalog.Resolve(clientName);
                ProgramKitOAuthTokenSourceValue? subject = null;
                ProgramKitOAuthTokenSourceValue? actor = null;
                if (profile.SubjectSourceIdentity is not null)
                {
                    subject = await tokenSource.GetAsync(profile.SubjectSourceIdentity, cancellationToken);
                    EnsureTokenKind(subject, profile.SubjectTokenKind!.Value, "subject");
                }
                if (profile.ActorSourceIdentity is not null)
                {
                    actor = await tokenSource.GetAsync(profile.ActorSourceIdentity, cancellationToken);
                    EnsureTokenKind(actor, profile.ActorTokenKind!.Value, "actor");
                }

                var cacheKey = CreateCacheKey(profile, subject, actor);
                if (cache.TryGetValue(cacheKey, out ProgramKitOAuthAccessToken? cached) &&
                    cached is not null &&
                    cached.ExpiresAt > DateTimeOffset.UtcNow.AddSeconds(profile.ExpirySkewSeconds))
                {
                    return cached;
                }

                using var activity = Activities.StartActivity("oauth.token", ActivityKind.Client);
                activity?.SetTag("oauth.client.name", profile.ClientName);
                activity?.SetTag("oauth.grant.kind", profile.GrantKind.ToString());
                Requests.Add(1, new KeyValuePair<string, object?>("oauth.client.name", profile.ClientName));
                var form = CreateForm(profile, subject, actor);
                using var request = new HttpRequestMessage(HttpMethod.Post, profile.TokenEndpoint);
                await ApplyClientAuthenticationAsync(profile, form, request, cancellationToken);
                request.Content = new FormUrlEncodedContent(form);
                using var response = await httpClientFactory
                    .CreateClient(string.Concat("ProgramKit.OAuth.", profile.ClientName))
                    .SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
                if (!response.IsSuccessStatusCode)
                {
                    activity?.SetTag("oauth.outcome", "rejected");
                    throw new InvalidOperationException(
                        string.Concat("OAuth token endpoint rejected profile ", profile.ClientName, "."));
                }

                var payload = await response.Content.ReadFromJsonAsync<ProgramKitOAuthTokenResponse>(
                    cancellationToken);
                if (payload is null)
                {
                    throw new InvalidOperationException("OAuth token response was empty.");
                }
                var accessToken = payload.AccessToken;
                var expiresIn = payload.ExpiresIn;
                var issuedKind = ParseIssuedKind(
                    payload.IssuedTokenType,
                    profile.ExpectedIssuedTokenKind,
                    profile.GrantKind == ProgramKitOAuthGrantKind.TokenExchangeRfc8693);
                var responseTokenType = payload.TokenType;
                var responseScope = payload.Scope ?? profile.Scope;
                if (string.IsNullOrWhiteSpace(accessToken) ||
                    !string.Equals(responseTokenType, "Bearer", StringComparison.OrdinalIgnoreCase) ||
                    !string.Equals(responseScope, profile.Scope, StringComparison.Ordinal) ||
                    expiresIn <= 0 ||
                    expiresIn > profile.RequestedLifetimeSeconds ||
                    issuedKind != profile.ExpectedIssuedTokenKind)
                {
                    activity?.SetTag("oauth.outcome", "invalid-response");
                    throw new InvalidOperationException(
                        string.Concat("OAuth token response violated profile ", profile.ClientName, "."));
                }

                var boundedLifetime = Math.Min(expiresIn, profile.MaximumCacheLifetimeSeconds);
                var result = new ProgramKitOAuthAccessToken(
                    accessToken,
                    issuedKind,
                    DateTimeOffset.UtcNow.AddSeconds(boundedLifetime));
                if (profile.CacheEnabled)
                {
                    cache.Set(cacheKey, result, result.ExpiresAt);
                }
                activity?.SetTag("oauth.outcome", "accepted");
                return result;
            }

            private async ValueTask ApplyClientAuthenticationAsync(
                ProgramKitOAuthProfile profile,
                Dictionary<string, string> form,
                HttpRequestMessage request,
                CancellationToken cancellationToken)
            {
                if (profile.AuthenticationMethod == "private_key_jwt")
                {
                    form["client_assertion_type"] =
                        "urn:ietf:params:oauth:client-assertion-type:jwt-bearer";
                    form["client_assertion"] = await assertionProvider.CreateAsync(
                        profile.AuthenticationReferenceIdentity,
                        profile.TokenEndpoint,
                        cancellationToken);
                    return;
                }

                var secret = profile.AuthenticationConfigurationKey is null
                    ? await credentialProvider.GetAsync(
                        profile.AuthenticationReferenceIdentity,
                        cancellationToken)
                    : configuration[profile.AuthenticationConfigurationKey];
                if (string.IsNullOrWhiteSpace(secret))
                {
                    throw new InvalidOperationException("OAuth client authentication material is unavailable.");
                }
                if (profile.AuthenticationMethod == "client_secret_basic")
                {
                    var basic = Convert.ToBase64String(
                        Encoding.UTF8.GetBytes(string.Concat(
                            Uri.EscapeDataString(profile.ClientId),
                            ":",
                            Uri.EscapeDataString(secret))));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Basic", basic);
                }
                else
                {
                    form["client_secret"] = secret;
                }
            }

            private static Dictionary<string, string> CreateForm(
                ProgramKitOAuthProfile profile,
                ProgramKitOAuthTokenSourceValue? subject,
                ProgramKitOAuthTokenSourceValue? actor)
            {
                var form = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["grant_type"] = profile.GrantKind == ProgramKitOAuthGrantKind.ClientCredentials
                        ? "client_credentials"
                        : "urn:ietf:params:oauth:grant-type:token-exchange",
                    ["client_id"] = profile.ClientId,
                    ["resource"] = profile.Resource.AbsoluteUri,
                    ["audience"] = profile.Audience,
                    ["scope"] = profile.Scope,
                };
                if (profile.GrantKind == ProgramKitOAuthGrantKind.TokenExchangeRfc8693)
                {
                    form["requested_token_type"] = Urn(profile.RequestedTokenKind);
                    form["subject_token"] = subject!.Value;
                    form["subject_token_type"] = Urn(subject.TokenKind);
                    if (actor is not null)
                    {
                        form["actor_token"] = actor.Value;
                        form["actor_token_type"] = Urn(actor.TokenKind);
                    }
                }
                return form;
            }

            private static string CreateCacheKey(
                ProgramKitOAuthProfile profile,
                ProgramKitOAuthTokenSourceValue? subject,
                ProgramKitOAuthTokenSourceValue? actor)
            {
                var dimensions = string.Join("\u001f",
                    profile.ClientName,
                    profile.GrantKind,
                    profile.ClientId,
                    profile.AuthenticationMethod,
                    profile.AuthenticationReferenceIdentity,
                    profile.Resource.AbsoluteUri,
                    profile.Audience,
                    profile.Scope,
                    profile.RequestedTokenKind,
                    profile.ExpectedIssuedTokenKind,
                    profile.ExchangeMode,
                    profile.RequestedLifetimeSeconds,
                    profile.MaximumCacheLifetimeSeconds,
                    subject?.ProvenanceIdentity,
                    subject?.TokenKind,
                    Digest(subject?.Value),
                    actor?.ProvenanceIdentity,
                    actor?.TokenKind,
                    Digest(actor?.Value));
                return string.Concat("ProgramKit.OAuth.", Digest(dimensions));
            }

            private static string Digest(string? value) =>
                value is null
                    ? "-"
                    : Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));

            private static void EnsureTokenKind(
                ProgramKitOAuthTokenSourceValue value,
                ProgramKitOAuthTokenKind expected,
                string role)
            {
                if (value.TokenKind != expected)
                {
                    throw new InvalidOperationException(
                        string.Concat("OAuth ", role, " token kind did not match the explicit profile."));
                }
            }

            private static ProgramKitOAuthTokenKind ParseIssuedKind(
                string? issuedTokenType,
                ProgramKitOAuthTokenKind fallback,
                bool required)
            {
                if (issuedTokenType is null)
                {
                    if (required)
                    {
                        throw new InvalidOperationException(
                            "RFC 8693 response omitted issued_token_type.");
                    }
                    return fallback;
                }
                return issuedTokenType switch
                {
                    "urn:ietf:params:oauth:token-type:access_token" => ProgramKitOAuthTokenKind.AccessToken,
                    "urn:ietf:params:oauth:token-type:jwt" => ProgramKitOAuthTokenKind.Jwt,
                    _ => throw new InvalidOperationException("OAuth token response has an unsupported issued token type."),
                };
            }

            private static string Urn(ProgramKitOAuthTokenKind kind) => kind switch
            {
                ProgramKitOAuthTokenKind.AccessToken => "urn:ietf:params:oauth:token-type:access_token",
                ProgramKitOAuthTokenKind.Jwt => "urn:ietf:params:oauth:token-type:jwt",
                _ => throw new InvalidOperationException("Unsupported OAuth token kind."),
            };
        }
        """;

    private static string RenderHandler() =>
        """
        // <auto-generated program-kit>
        #nullable enable
        using System.Net.Http.Headers;

        namespace GeneratedHost.Hosting;

        internal sealed class ProgramKitOAuthBearerHandler(
            string clientName,
            ProgramKitOAuthTokenEndpointClient tokenClient) : DelegatingHandler
        {
            protected override async Task<HttpResponseMessage> SendAsync(
                HttpRequestMessage request,
                CancellationToken cancellationToken)
            {
                var token = await tokenClient.GetAsync(clientName, cancellationToken);
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token.Value);
                return await base.SendAsync(request, cancellationToken);
            }
        }
        """;

    private static GeneratedOutput Output(string typeName, string source) =>
        new(
            string.Concat("ProgramKitGenerated/Hosting/", typeName, ".cs"),
            DotNetSourceText.Utf8(source));

    private static StringBuilder Source()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated program-kit>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace GeneratedHost.Hosting;");
        builder.AppendLine();
        return builder;
    }

    private static string Authentication(DotNetOAuthClientAuthenticationMethod method) =>
        method switch
        {
            DotNetOAuthClientAuthenticationMethod.ClientSecretBasic => "client_secret_basic",
            DotNetOAuthClientAuthenticationMethod.ClientSecretPost => "client_secret_post",
            DotNetOAuthClientAuthenticationMethod.PrivateKeyJwtAssertion => "private_key_jwt",
            _ => throw new InvalidOperationException("Unsupported OAuth client authentication."),
        };

    private static string TokenKind(DotNetOAuthTokenType tokenType) =>
        tokenType switch
        {
            DotNetOAuthTokenType.AccessToken => "AccessToken",
            DotNetOAuthTokenType.Jwt => "Jwt",
            _ => throw new InvalidOperationException("Unsupported OAuth token type."),
        };

    private static string Scope(ImmutableArray<string> scopes) =>
        string.Join(" ", scopes.Order(StringComparer.Ordinal));

    private static string Literal(string value) =>
        DotNetSourceText.CSharpLiteral(value);

    private static string NullableLiteral(string? value) =>
        value is null ? "null" : Literal(value);
}
