using System.Text;
using Orbyss.ProgramKit.SecretResolution.Contracts;
using Orbyss.ProgramKit.SecretResolution.Contracts.Validation;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation;

/// <summary>Deterministic compiler for bounded, disposable secret-change subscriptions.</summary>
public sealed class DotNetSecretSubscriptionCompiler :
    IDotNetSecretSubscriptionCompiler
{
    private readonly IProgramKitSemanticValidator<SecretResolutionContract> contractValidator;

    /// <summary>Initializes the compiler with the provider-neutral contract validator.</summary>
    public DotNetSecretSubscriptionCompiler(
        IProgramKitSemanticValidator<SecretResolutionContract> contractValidator)
    {
        ArgumentNullException.ThrowIfNull(contractValidator);
        this.contractValidator = contractValidator;
    }

    /// <inheritdoc />
    public ImmutableArray<GeneratedOutput> Compile(
        DotNetSecretSubscriptionDefinition definition)
    {
        Validate(definition);
        if (!definition.Contract.Consumption.RotationRequired ||
            definition.Contract.Consumption.Reaction ==
            SecretConsumerReaction.Unsupported)
        {
            return [];
        }

        return
        [
            Output(
                string.Concat(
                    "ProgramKitGenerated/Hosting/",
                    definition.TypeName,
                    ".cs"),
                RenderSubscription(definition)),
            Output(
                string.Concat(
                    "ProgramKitGenerated/Hosting/I",
                    definition.TypeName,
                    "ReactionConsumer.cs"),
                RenderConsumerBoundary(definition)),
        ];
    }

    /// <inheritdoc />
    public string RenderRegistration(DotNetSecretSubscriptionDefinition definition)
    {
        Validate(definition);
        return !definition.Contract.Consumption.RotationRequired ||
               definition.Contract.Consumption.Reaction ==
               SecretConsumerReaction.Unsupported
            ? string.Empty
            : string.Concat(
                "services.AddHostedService<",
                definition.Namespace,
                ".",
                definition.TypeName,
                ">();");
    }

    private void Validate(DotNetSecretSubscriptionDefinition definition)
    {
        ArgumentNullException.ThrowIfNull(definition);
        var contractResult = contractValidator.Validate(definition.Contract);
        if (!contractResult.IsValid)
        {
            throw new ArgumentException(
                string.Join(
                    Environment.NewLine,
                    contractResult.Diagnostics.Select(static diagnostic =>
                        string.Concat(
                            diagnostic.Id,
                            " ",
                            diagnostic.Path,
                            " ",
                            diagnostic.Message))),
                nameof(definition));
        }

        if (!IsQualifiedName(definition.Namespace) ||
            !IsIdentifier(definition.TypeName))
        {
            throw new ArgumentException(
                "The generated namespace and type name must be explicit valid C# identifiers.",
                nameof(definition));
        }

        if (definition.QueueCapacity is < 1 or > 1024)
        {
            throw new ArgumentOutOfRangeException(
                nameof(definition),
                "The bounded reaction queue capacity must be between 1 and 1024.");
        }
    }

    private static string RenderSubscription(
        DotNetSecretSubscriptionDefinition definition)
    {
        var contract = definition.Contract;
        var referenceIdentity = contract.Reference.Identity.Value;
        var reaction = contract.Consumption.Reaction.ToString();
        var consumerType = string.Concat("I", definition.TypeName, "ReactionConsumer");
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated program-kit>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Threading.Channels;");
        builder.AppendLine("using Microsoft.Extensions.Hosting;");
        builder.AppendLine("using Orbyss.ProgramKit.Artifacts.Primitives;");
        builder.AppendLine("using Orbyss.ProgramKit.SecretResolution.Contracts;");
        builder.AppendLine("using Orbyss.ProgramKit.SecretResolution.Contracts.Validation;");
        builder.AppendLine("using Orbyss.ProgramKit.SecretResolution.Contracts.Runtime;");
        builder.AppendLine();
        builder.Append("namespace ").Append(definition.Namespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Queues metadata-only secret changes for one consumer-owned reaction.</summary>");
        builder
            .Append("public sealed class ")
            .Append(definition.TypeName)
            .AppendLine(" : BackgroundService");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly ProgramKitIdentifier QueueFullCode =");
        builder.AppendLine("        new(\"pkid:diagnostic:program-kit:secret-reaction-queue-full\");");
        builder.AppendLine("    private static readonly ProgramKitIdentifier InvalidResultCode =");
        builder.AppendLine("        new(\"pkid:diagnostic:program-kit:secret-reaction-invalid-result\");");
        builder.AppendLine("    private static readonly ProgramKitIdentifier ConsumerFailureCode =");
        builder.AppendLine("        new(\"pkid:diagnostic:program-kit:secret-reaction-consumer-failed\");");
        builder.AppendLine("    private static readonly ProgramKitIdentifier InvalidSignalCode =");
        builder.AppendLine("        new(\"pkid:diagnostic:program-kit:secret-change-signal-invalid\");");
        builder.AppendLine("    private static readonly ProgramKitIdentifier ReferenceIdentity =");
        builder
            .Append("        new(")
            .Append(DotNetSourceText.CSharpLiteral(referenceIdentity))
            .AppendLine(");");
        builder.AppendLine("    private readonly ISecretChangeSource changeSource;");
        builder
            .Append("    private readonly ")
            .Append(consumerType)
            .AppendLine(" consumer;");
        builder.AppendLine("    private readonly ISecretReactionOutcomeSink outcomeSink;");
        builder.AppendLine("    private readonly Channel<SecretReactionRequest> changes =");
        builder.AppendLine("        Channel.CreateBounded<SecretReactionRequest>(");
        builder
            .Append("            new BoundedChannelOptions(")
            .Append(definition.QueueCapacity)
            .AppendLine(")");
        builder.AppendLine("            {");
        builder.AppendLine("                FullMode = BoundedChannelFullMode.Wait,");
        builder.AppendLine("                SingleReader = true,");
        builder.AppendLine("                SingleWriter = false,");
        builder.AppendLine("            });");
        builder.AppendLine("    private IDisposable? subscription;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Initializes the bounded subscription with provider- and consumer-owned services.</summary>");
        builder
            .Append("    public ")
            .Append(definition.TypeName)
            .AppendLine("(");
        builder.AppendLine("        ISecretChangeSource changeSource,");
        builder
            .Append("        ")
            .Append(consumerType)
            .AppendLine(" consumer,");
        builder.AppendLine("        ISecretReactionOutcomeSink outcomeSink)");
        builder.AppendLine("    {");
        builder.AppendLine("        this.changeSource = changeSource;");
        builder.AppendLine("        this.consumer = consumer;");
        builder.AppendLine("        this.outcomeSink = outcomeSink;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public override Task StartAsync(CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        builder.AppendLine("        subscription = changeSource.Subscribe(");
        builder.AppendLine("            ReferenceIdentity,");
        builder.AppendLine("            signal =>");
        builder.AppendLine("            {");
        builder.AppendLine("                var generation = signal.Lifecycle?.Generation ?? 0;");
        builder.AppendLine("                if (signal.ReferenceIdentity != ReferenceIdentity ||");
        builder.AppendLine("                    !SecretChangeSignalValidator.ValidateSignal(signal).IsValid)");
        builder.AppendLine("                {");
        builder.AppendLine("                    outcomeSink.Report(new SecretReactionResult(");
        builder.AppendLine("                        ReferenceIdentity,");
        builder.AppendLine("                        generation,");
        builder
            .Append("                        SecretConsumerReaction.")
            .Append(reaction)
            .AppendLine(",");
        builder.AppendLine("                        SecretReactionStatus.Failed,");
        builder.AppendLine("                        InvalidSignalCode));");
        builder.AppendLine("                    return;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                var request = new SecretReactionRequest(");
        builder.AppendLine("                    signal,");
        builder
            .Append("                    SecretConsumerReaction.")
            .Append(reaction)
            .AppendLine(");");
        builder.AppendLine("                if (!changes.Writer.TryWrite(request))");
        builder.AppendLine("                {");
        builder.AppendLine("                    outcomeSink.Report(new SecretReactionResult(");
        builder.AppendLine("                        signal.ReferenceIdentity,");
        builder.AppendLine("                        generation,");
        builder
            .Append("                        SecretConsumerReaction.")
            .Append(reaction)
            .AppendLine(",");
        builder.AppendLine("                        SecretReactionStatus.Rejected,");
        builder.AppendLine("                        QueueFullCode));");
        builder.AppendLine("                }");
        builder.AppendLine("            });");
        builder.AppendLine("        return base.StartAsync(cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    protected override async Task ExecuteAsync(CancellationToken stoppingToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        await foreach (var request in changes.Reader.ReadAllAsync(stoppingToken))");
        builder.AppendLine("        {");
        builder.AppendLine("            SecretReactionResult result;");
        builder.AppendLine("            try");
        builder.AppendLine("            {");
        builder.AppendLine("                result = await consumer.ApplyAsync(request, stoppingToken);");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)");
        builder.AppendLine("            {");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (Exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                result = Failure(request, ConsumerFailureCode);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            if (!Matches(request, result) ||");
        builder.AppendLine("                !SecretReactionResultValidator.ValidateResult(result).IsValid)");
        builder.AppendLine("            {");
        builder.AppendLine("                result = Failure(request, InvalidResultCode);");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            outcomeSink.Report(result);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine("    public override void Dispose()");
        builder.AppendLine("    {");
        builder.AppendLine("        subscription?.Dispose();");
        builder.AppendLine("        subscription = null;");
        builder.AppendLine("        changes.Writer.TryComplete();");
        builder.AppendLine("        base.Dispose();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static bool Matches(");
        builder.AppendLine("        SecretReactionRequest request,");
        builder.AppendLine("        SecretReactionResult result) =>");
        builder.AppendLine("        result.ReferenceIdentity == request.Signal.ReferenceIdentity &&");
        builder.AppendLine("        result.Generation == request.Signal.Lifecycle.Generation &&");
        builder.AppendLine("        result.Reaction == request.Reaction;");
        builder.AppendLine();
        builder.AppendLine("    private static SecretReactionResult Failure(");
        builder.AppendLine("        SecretReactionRequest request,");
        builder.AppendLine("        ProgramKitIdentifier code) =>");
        builder.AppendLine("        new(");
        builder.AppendLine("            request.Signal.ReferenceIdentity,");
        builder.AppendLine("            request.Signal.Lifecycle.Generation,");
        builder.AppendLine("            request.Reaction,");
        builder.AppendLine("            SecretReactionStatus.Failed,");
        builder.AppendLine("            code);");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderConsumerBoundary(
        DotNetSecretSubscriptionDefinition definition)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated program-kit>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Orbyss.ProgramKit.SecretResolution.Contracts.Runtime;");
        builder.AppendLine();
        builder.Append("namespace ").Append(definition.Namespace).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Consumer-owned implementation of the selected lifecycle reaction.</summary>");
        builder
            .Append("public interface I")
            .Append(definition.TypeName)
            .AppendLine("ReactionConsumer : ISecretReactionConsumer;");
        return builder.ToString();
    }

    private static bool IsQualifiedName(string value) =>
        !string.IsNullOrWhiteSpace(value) &&
        value.Split('.').All(IsIdentifier);

    private static bool IsIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value) ||
            !(char.IsLetter(value[0]) || value[0] == '_'))
        {
            return false;
        }

        return value.Skip(1).All(static character =>
            char.IsLetterOrDigit(character) || character == '_');
    }

    private static GeneratedOutput Output(string path, string text) =>
        new(path, DotNetSourceText.Utf8(text));
}
