using System.Text;
using Orbyss.ProgramKit.DotNet.Operations.TransportFailures;
using Orbyss.ProgramKit.DotNet.Shells;
using Orbyss.ProgramKit.Operations.Contracts.Transport;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation;

/// <summary>Deterministic .NET 10 Problem Details and exception-handler compiler.</summary>
public sealed class DotNetTransportFailureProjectionCompiler :
    IDotNetTransportFailureProjectionCompiler
{
    /// <inheritdoc />
    public ImmutableArray<GeneratedOutput> Compile(DotNetHostDefinition host)
    {
        ArgumentNullException.ThrowIfNull(host);
        if (host.TransportFailures is null)
        {
            return [];
        }

        var configuration = host.TransportFailures;
        var fallback = configuration.Profile.Failures.Single(
            failure => failure.Identity == configuration.Profile.GenericFallbackIdentity);
        var failures = configuration.Profile.Failures.ToDictionary(
            static failure => failure.Identity.Value,
            StringComparer.Ordinal);
        return
        [
            Output(
                "ProgramKitTransportFailureDiagnostics",
                RenderDiagnostics()),
            Output(
                "ProgramKitTransportFailureCategory",
                RenderCategory()),
            Output(
                "ProgramKitProblemDetailsWriter",
                RenderWriter()),
            Output(
                "ProgramKitClientDisconnectExceptionHandler",
                RenderDisconnectHandler()),
            Output(
                "ProgramKitMappedTransportFailureHandler",
                RenderMappedHandler(configuration.ExceptionMappings, failures)),
            Output(
                "ProgramKitFallbackTransportFailureHandler",
                RenderFallbackHandler(fallback)),
        ];
    }

    /// <inheritdoc />
    public string RenderRegistration(DotNetHostDefinition host)
    {
        ArgumentNullException.ThrowIfNull(host);
        if (host.TransportFailures is null)
        {
            return string.Empty;
        }

        return """
            builder.Services.AddProblemDetails(options =>
            {
                options.CustomizeProblemDetails = context =>
                {
                    context.ProblemDetails.Extensions["traceId"] =
                        global::System.Diagnostics.Activity.Current?.TraceId.ToString() ??
                        context.HttpContext.TraceIdentifier;
                };
            });
            builder.Services.AddExceptionHandler<global::GeneratedHost.Hosting.ProgramKitClientDisconnectExceptionHandler>();
            builder.Services.AddExceptionHandler<global::GeneratedHost.Hosting.ProgramKitMappedTransportFailureHandler>();
            builder.Services.AddExceptionHandler<global::GeneratedHost.Hosting.ProgramKitFallbackTransportFailureHandler>();
            """;
    }

    /// <inheritdoc />
    public string RenderMiddleware(DotNetHostDefinition host)
    {
        ArgumentNullException.ThrowIfNull(host);
        if (host.TransportFailures is null)
        {
            return string.Empty;
        }

        var builder = new StringBuilder();
        builder.AppendLine("app.UseExceptionHandler(new global::Microsoft.AspNetCore.Builder.ExceptionHandlerOptions");
        builder.AppendLine("{");
        builder.AppendLine("    SuppressDiagnosticsCallback = static _ => true,");
        builder.AppendLine("});");
        if (host.TransportFailures.StatusCodePages)
        {
            builder.AppendLine("app.UseStatusCodePages(async statusCodeContext =>");
            builder.AppendLine("{");
            builder.AppendLine("    var problemDetails = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions");
            builder.AppendLine("        .GetRequiredService<global::Microsoft.AspNetCore.Http.IProblemDetailsService>(");
            builder.AppendLine("            statusCodeContext.HttpContext.RequestServices);");
            builder.AppendLine("    _ = await problemDetails.TryWriteAsync(new global::Microsoft.AspNetCore.Http.ProblemDetailsContext");
            builder.AppendLine("    {");
            builder.AppendLine("        HttpContext = statusCodeContext.HttpContext,");
            builder.AppendLine("    });");
            builder.AppendLine("});");
        }

        return builder.ToString();
    }

    private static GeneratedOutput Output(string typeName, string source) =>
        new(
            string.Concat("ProgramKitGenerated/Hosting/", typeName, ".cs"),
            DotNetSourceText.Utf8(source));

    private static StringBuilder Source(params string[] namespaces)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated program-kit>");
        builder.AppendLine("#nullable enable");
        foreach (var item in namespaces)
        {
            builder.Append("using ").Append(item).AppendLine(";");
        }

        builder.AppendLine();
        builder.AppendLine("namespace GeneratedHost.Hosting;");
        builder.AppendLine();
        return builder;
    }

    private static string RenderDiagnostics()
    {
        var builder = Source(
            "System.Diagnostics",
            "System.Diagnostics.Metrics",
            "Microsoft.Extensions.Logging");
        builder.AppendLine("internal static partial class ProgramKitTransportFailureDiagnostics");
        builder.AppendLine("{");
        builder.AppendLine("    internal const string MeterName = \"Orbyss.ProgramKit.TransportFailures\";");
        builder.AppendLine("    private static readonly Meter Meter = new(MeterName, \"1.0.0\");");
        builder.AppendLine("    private static readonly Counter<long> Outcomes = Meter.CreateCounter<long>(");
        builder.AppendLine("        \"program_kit.transport.failure.outcomes\",");
        builder.AppendLine("        \"{outcome}\",");
        builder.AppendLine("        \"Sanitized handled transport-failure outcomes.\");");
        builder.AppendLine();
        builder.AppendLine("    [LoggerMessage(EventId = 19001, EventName = \"TransportFailureHandled\", Level = LogLevel.Warning,");
        builder.AppendLine("        Message = \"Transport failure {FailureIdentity} produced status {StatusCode} with outcome {Outcome}.\")]");
        builder.AppendLine("    private static partial void WriteHandled(");
        builder.AppendLine("        ILogger logger, string failureIdentity, int statusCode, string outcome);");
        builder.AppendLine();
        builder.AppendLine("    internal static void Record(ILogger logger, string failureIdentity, int statusCode, string outcome)");
        builder.AppendLine("    {");
        builder.AppendLine("        WriteHandled(logger, failureIdentity, statusCode, outcome);");
        builder.AppendLine("        Outcomes.Add(1,");
        builder.AppendLine("            new KeyValuePair<string, object?>(\"failure.identity\", failureIdentity),");
        builder.AppendLine("            new KeyValuePair<string, object?>(\"http.response.status_code\", statusCode),");
        builder.AppendLine("            new KeyValuePair<string, object?>(\"outcome\", outcome));");
        builder.AppendLine("        Activity.Current?.SetTag(\"program_kit.failure.identity\", failureIdentity);");
        builder.AppendLine("        Activity.Current?.SetStatus(ActivityStatusCode.Error);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderCategory()
    {
        var builder = Source();
        builder.AppendLine("internal sealed class ProgramKitTransportFailureCategory");
        builder.AppendLine("{");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderWriter()
    {
        var builder = Source(
            "Microsoft.AspNetCore.Http",
            "Microsoft.AspNetCore.Mvc",
            "Microsoft.Extensions.Hosting",
            "Microsoft.Extensions.Logging");
        builder.AppendLine("internal static class ProgramKitProblemDetailsWriter");
        builder.AppendLine("{");
        builder.AppendLine("    internal static async ValueTask<bool> WriteAsync(");
        builder.AppendLine("        HttpContext context,");
        builder.AppendLine("        IProblemDetailsService service,");
        builder.AppendLine("        IHostEnvironment environment,");
        builder.AppendLine("        ILogger logger,");
        builder.AppendLine("        string identity,");
        builder.AppendLine("        int statusCode,");
        builder.AppendLine("        string type,");
        builder.AppendLine("        string title,");
        builder.AppendLine("        string productionDetail,");
        builder.AppendLine("        string developmentDetail)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (context.Response.HasStarted)");
        builder.AppendLine("        {");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        context.Response.StatusCode = statusCode;");
        builder.AppendLine("        var problem = new ProblemDetails");
        builder.AppendLine("        {");
        builder.AppendLine("            Status = statusCode,");
        builder.AppendLine("            Type = type,");
        builder.AppendLine("            Title = title,");
        builder.AppendLine("            Detail = environment.IsDevelopment() ? developmentDetail : productionDetail,");
        builder.AppendLine("            Instance = context.Request.Path,");
        builder.AppendLine("        };");
        builder.AppendLine("        _ = await service.TryWriteAsync(new ProblemDetailsContext");
        builder.AppendLine("        {");
        builder.AppendLine("            HttpContext = context,");
        builder.AppendLine("            ProblemDetails = problem,");
        builder.AppendLine("        });");
        builder.AppendLine("        ProgramKitTransportFailureDiagnostics.Record(logger, identity, statusCode, \"handled\");");
        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderDisconnectHandler()
    {
        var builder = Source(
            "Microsoft.AspNetCore.Diagnostics",
            "Microsoft.AspNetCore.Http",
            "Microsoft.Extensions.Logging");
        builder.AppendLine("internal sealed class ProgramKitClientDisconnectExceptionHandler : IExceptionHandler");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;");
        builder.AppendLine();
        builder.AppendLine("    public ProgramKitClientDisconnectExceptionHandler(");
        builder.AppendLine("        ILogger<ProgramKitTransportFailureCategory> logger)");
        builder.AppendLine("    {");
        builder.AppendLine("        _logger = logger;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public ValueTask<bool> TryHandleAsync(HttpContext context, Exception exception, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (exception is not OperationCanceledException || !context.RequestAborted.IsCancellationRequested)");
        builder.AppendLine("        {");
        builder.AppendLine("            return ValueTask.FromResult(false);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        ProgramKitTransportFailureDiagnostics.Record(_logger, \"pkid:failure:transport:client-disconnect\", 0, \"client-disconnect\");");
        builder.AppendLine("        context.Abort();");
        builder.AppendLine("        return ValueTask.FromResult(true);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderMappedHandler(
        ImmutableArray<DotNetExceptionFailureMapping> mappings,
        Dictionary<string, TransportFailureContract> failures)
    {
        var builder = Source(
            "Microsoft.AspNetCore.Diagnostics",
            "Microsoft.AspNetCore.Http",
            "Microsoft.Extensions.Hosting",
            "Microsoft.Extensions.Logging");
        builder.AppendLine("internal sealed class ProgramKitMappedTransportFailureHandler : IExceptionHandler");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly IProblemDetailsService _service;");
        builder.AppendLine("    private readonly IHostEnvironment _environment;");
        builder.AppendLine("    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;");
        builder.AppendLine();
        builder.AppendLine("    public ProgramKitMappedTransportFailureHandler(");
        builder.AppendLine("        IProblemDetailsService service,");
        builder.AppendLine("        IHostEnvironment environment,");
        builder.AppendLine("        ILogger<ProgramKitTransportFailureCategory> logger)");
        builder.AppendLine("    {");
        builder.AppendLine("        _service = service;");
        builder.AppendLine("        _environment = environment;");
        builder.AppendLine("        _logger = logger;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public ValueTask<bool> TryHandleAsync(HttpContext context, Exception exception, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (context.Response.HasStarted || exception is OperationCanceledException)");
        builder.AppendLine("        {");
        builder.AppendLine("            return ValueTask.FromResult(false);");
        builder.AppendLine("        }");
        foreach (var mapping in mappings.OrderBy(static item => item.Order))
        {
            var failure = failures[mapping.FailureIdentity.Value];
            builder
                .Append("        if (exception is global::")
                .Append(mapping.ExceptionType)
                .AppendLine(")");
            builder.AppendLine("        {");
            builder.Append("            return ProgramKitProblemDetailsWriter.WriteAsync(context, _service, _environment, _logger, ");
            AppendFailureArguments(builder, failure);
            builder.AppendLine(");");
            builder.AppendLine("        }");
        }

        builder.AppendLine("        return ValueTask.FromResult(false);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderFallbackHandler(TransportFailureContract failure)
    {
        var builder = Source(
            "Microsoft.AspNetCore.Diagnostics",
            "Microsoft.AspNetCore.Http",
            "Microsoft.Extensions.Hosting",
            "Microsoft.Extensions.Logging");
        builder.AppendLine("internal sealed class ProgramKitFallbackTransportFailureHandler : IExceptionHandler");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly IProblemDetailsService _service;");
        builder.AppendLine("    private readonly IHostEnvironment _environment;");
        builder.AppendLine("    private readonly ILogger<ProgramKitTransportFailureCategory> _logger;");
        builder.AppendLine();
        builder.AppendLine("    public ProgramKitFallbackTransportFailureHandler(");
        builder.AppendLine("        IProblemDetailsService service,");
        builder.AppendLine("        IHostEnvironment environment,");
        builder.AppendLine("        ILogger<ProgramKitTransportFailureCategory> logger)");
        builder.AppendLine("    {");
        builder.AppendLine("        _service = service;");
        builder.AppendLine("        _environment = environment;");
        builder.AppendLine("        _logger = logger;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public ValueTask<bool> TryHandleAsync(HttpContext context, Exception exception, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (context.Response.HasStarted || exception is OperationCanceledException)");
        builder.AppendLine("        {");
        builder.AppendLine("            return ValueTask.FromResult(false);");
        builder.AppendLine("        }");
        builder.Append("        return ProgramKitProblemDetailsWriter.WriteAsync(context, _service, _environment, _logger, ");
        AppendFailureArguments(builder, failure);
        builder.AppendLine(");");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendFailureArguments(
        StringBuilder builder,
        TransportFailureContract failure)
    {
        builder
            .Append(DotNetSourceText.CSharpLiteral(failure.Identity.Value)).Append(", ")
            .Append(failure.StatusCode).Append(", ")
            .Append(DotNetSourceText.CSharpLiteral(failure.Type.AbsoluteUri)).Append(", ")
            .Append(DotNetSourceText.CSharpLiteral(failure.Title)).Append(", ")
            .Append(DotNetSourceText.CSharpLiteral(failure.ProductionDetail)).Append(", ")
            .Append(DotNetSourceText.CSharpLiteral(failure.DevelopmentDetail));
    }
}
