<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><ImportDirectoryBuildProps>false</ImportDirectoryBuildProps><ImportDirectoryBuildTargets>false</ImportDirectoryBuildTargets><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><NuGetAudit>false</NuGetAudit></PropertyGroup><ItemGroup><PackageReference Include="CShells.AspNetCore" Version="0.0.29-preview.147"/><PackageReference Include="Orbyss.Foundation.WebDefaults" Version="0.2.2"/><PackageReference Include="Orbyss.Foundation.Web.ProblemDetails" Version="0.2.2"/><PackageReference Include="Orbyss.Foundation.Json.AspNetCore" Version="0.2.2"/><PackageReference Include="Orbyss.Foundation.Web.HostedPages" Version="0.2.2"/></ItemGroup></Project>
