<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ProgramKit.IsolatedConsumers.Contracts</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Orbyss.ProgramKit.Tasks.Core" Version="[0.1.0-alpha.1]" />
  </ItemGroup>
</Project>
