// <auto-generated program-kit>
#nullable enable
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Exercises the exact generated registrations in an isolated consumer.</summary>
public static class ConfigurationProviderComposition
{
    /// <summary>Adds all reviewed provider shapes in explicit precedence order.</summary>
    public static void AddReviewedProviders(
        HostApplicationBuilder builder,
        string[] args,
        string jsonPath,
        string keyPerFilePath)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(args);
        ArgumentException.ThrowIfNullOrWhiteSpace(jsonPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(keyPerFilePath);

        builder.Configuration.AddJsonFile(
            jsonPath,
            optional: false,
            reloadOnChange: true);
        builder.Configuration.AddEnvironmentVariables("PKHT_");
        builder.Configuration.AddCommandLine(args);
        builder.Configuration.AddInMemoryCollection(
            new Dictionary<string, string?>(StringComparer.Ordinal)
            {
                ["Generated:PublicValue"] = "in-memory",
            });
        if (builder.Environment.IsDevelopment())
        {
            builder.Configuration.AddUserSecrets(
                "program-kit-w030-conformance",
                reloadOnChange: true);
        }

        builder.Configuration.AddKeyPerFile(
            keyPerFilePath,
            optional: false,
            reloadOnChange: true);
        var programKitChainedConfiguration6 = new ConfigurationBuilder();
        programKitChainedConfiguration6.AddInMemoryCollection(
            new Dictionary<string, string?>(StringComparer.Ordinal)
            {
                ["Generated:ChainedValue"] = "chained",
            });
        builder.Configuration.AddConfiguration(
            programKitChainedConfiguration6.Build(),
            shouldDisposeConfiguration: true);
    }
}
