// <auto-generated program-kit>
#nullable enable
using System.ComponentModel.DataAnnotations;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Generated typed configuration used by the isolated consumer.</summary>
public sealed class GeneratedConsumerOptions
{
    /// <summary>Gets or sets the bounded sample count.</summary>
    [Required]
    [Range(1, 10)]
    public int? Count { get; set; }
}
