// <auto-generated program-kit>
#nullable enable
using Microsoft.Extensions.Options;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Source-generated validator for the isolated consumer Options.</summary>
[OptionsValidator]
public sealed partial class GeneratedConsumerOptionsValidator :
    IValidateOptions<GeneratedConsumerOptions>
{
}
