// <auto-generated program-kit>
#nullable enable

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Consumer-owned reaction to one validated monitored Options value.</summary>
public interface IQueuedConsumerOptionsChangeConsumer
{
    /// <summary>Consumes one bounded queued change.</summary>
    ValueTask ConsumeAsync(
        QueuedConsumerOptions value,
        string optionsName,
        CancellationToken cancellationToken);
}
