// <auto-generated program-kit>
#nullable enable
using System.ComponentModel.DataAnnotations;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Generated Options used to compile the bounded monitor projection.</summary>
public sealed class QueuedConsumerOptions
{
    /// <summary>Gets or sets the bounded sample count.</summary>
    [Required]
    public int? Count { get; set; }
}
