// <auto-generated program-kit>
#nullable enable
using System.Threading.Channels;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Queues validated monitored Options for consumer-owned reactions.</summary>
public sealed class QueuedConsumerOptionsMonitorSubscription :
    BackgroundService
{
    private readonly IEnumerable<IQueuedConsumerOptionsChangeConsumer> consumers;
    private readonly IOptionsMonitor<QueuedConsumerOptions> monitor;
    private readonly ILogger<QueuedConsumerOptions> logger;
    private readonly Channel<(QueuedConsumerOptions Value, string Name)> changes =
        Channel.CreateBounded<(QueuedConsumerOptions Value, string Name)>(
            new BoundedChannelOptions(1)
            {
                FullMode = BoundedChannelFullMode.DropOldest,
                SingleReader = true,
                SingleWriter = false,
            });
    private IDisposable? subscription;

    /// <summary>Initializes the bounded queue.</summary>
    public QueuedConsumerOptionsMonitorSubscription(
        IOptionsMonitor<QueuedConsumerOptions> monitor,
        IEnumerable<IQueuedConsumerOptionsChangeConsumer> consumers,
        ILogger<QueuedConsumerOptions> logger)
    {
        this.monitor = monitor;
        this.consumers = consumers;
        this.logger = logger;
    }

    /// <inheritdoc />
    public override Task StartAsync(CancellationToken cancellationToken)
    {
        subscription = monitor.OnChange((value, optionsName) =>
        {
            var normalizedOptionsName = optionsName ?? Options.DefaultName;
            if (!string.Equals(
                    normalizedOptionsName,
                    string.Empty,
                    StringComparison.Ordinal))
            {
                return;
            }

            changes.Writer.TryWrite((value, normalizedOptionsName));
            logger.LogInformation(
                "Validated configuration change queued for {DefinitionIdentity} and Options name {OptionsName}; values and references are redacted.",
                "pkid:configuration:fixture:queued-consumer",
                normalizedOptionsName);
        });
        return base.StartAsync(cancellationToken);
    }

    /// <inheritdoc />
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await foreach (var change in changes.Reader.ReadAllAsync(stoppingToken))
        {
            foreach (var consumer in consumers)
            {
                await consumer.ConsumeAsync(
                    change.Value,
                    change.Name,
                    stoppingToken);
            }
        }
    }

    /// <inheritdoc />
    public override void Dispose()
    {
        subscription?.Dispose();
        subscription = null;
        changes.Writer.TryComplete();
        base.Dispose();
    }
}
