// <auto-generated program-kit>
#nullable enable
using Microsoft.Extensions.Options;

namespace Orbyss.ProgramKit.ConfigurationConsumerFixture.Configuration;

/// <summary>Source-generated validator for queued consumer Options.</summary>
[OptionsValidator]
public sealed partial class QueuedConsumerOptionsValidator :
    IValidateOptions<QueuedConsumerOptions>
{
}
