// <auto-generated program-kit>
#nullable enable
using System.Threading.Channels;
using Microsoft.Extensions.Hosting;
using Orbyss.ProgramKit.Artifacts.Primitives;
using Orbyss.ProgramKit.SecretResolution.Contracts;
using Orbyss.ProgramKit.SecretResolution.Contracts.Runtime;
using Orbyss.ProgramKit.SecretResolution.Contracts.Validation;

namespace Orbyss.ProgramKit.SecretResolutionConsumerFixture.Hosting;

/// <summary>Queues metadata-only secret changes for one consumer-owned reaction.</summary>
public sealed class FixtureSecretSubscription : BackgroundService
{
    private static readonly ProgramKitIdentifier QueueFullCode =
        new("pkid:diagnostic:program-kit:secret-reaction-queue-full");
    private static readonly ProgramKitIdentifier InvalidResultCode =
        new("pkid:diagnostic:program-kit:secret-reaction-invalid-result");
    private static readonly ProgramKitIdentifier ConsumerFailureCode =
        new("pkid:diagnostic:program-kit:secret-reaction-consumer-failed");
    private static readonly ProgramKitIdentifier InvalidSignalCode =
        new("pkid:diagnostic:program-kit:secret-change-signal-invalid");
    private static readonly ProgramKitIdentifier ReferenceIdentity =
        new("pkid:secret-reference:fixture:service-credential");
    private readonly ISecretChangeSource changeSource;
    private readonly IFixtureSecretSubscriptionReactionConsumer consumer;
    private readonly ISecretReactionOutcomeSink outcomeSink;
    private readonly Channel<SecretReactionRequest> changes =
        Channel.CreateBounded<SecretReactionRequest>(
            new BoundedChannelOptions(1)
            {
                FullMode = BoundedChannelFullMode.Wait,
                SingleReader = true,
                SingleWriter = false,
            });
    private IDisposable? subscription;

    /// <summary>Initializes the bounded subscription with provider- and consumer-owned services.</summary>
    public FixtureSecretSubscription(
        ISecretChangeSource changeSource,
        IFixtureSecretSubscriptionReactionConsumer consumer,
        ISecretReactionOutcomeSink outcomeSink)
    {
        this.changeSource = changeSource;
        this.consumer = consumer;
        this.outcomeSink = outcomeSink;
    }

    /// <inheritdoc />
    public override Task StartAsync(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        subscription = changeSource.Subscribe(
            ReferenceIdentity,
            signal =>
            {
                var generation = signal.Lifecycle?.Generation ?? 0;
                if (signal.ReferenceIdentity != ReferenceIdentity ||
                    !SecretChangeSignalValidator.ValidateSignal(signal).IsValid)
                {
                    outcomeSink.Report(new SecretReactionResult(
                        ReferenceIdentity,
                        generation,
                        SecretConsumerReaction.Reconnect,
                        SecretReactionStatus.Failed,
                        InvalidSignalCode));
                    return;
                }

                var request = new SecretReactionRequest(
                    signal,
                    SecretConsumerReaction.Reconnect);
                if (!changes.Writer.TryWrite(request))
                {
                    outcomeSink.Report(new SecretReactionResult(
                        signal.ReferenceIdentity,
                        generation,
                        SecretConsumerReaction.Reconnect,
                        SecretReactionStatus.Rejected,
                        QueueFullCode));
                }
            });
        return base.StartAsync(cancellationToken);
    }

    /// <inheritdoc />
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await foreach (var request in changes.Reader.ReadAllAsync(stoppingToken))
        {
            SecretReactionResult result;
            try
            {
                result = await consumer.ApplyAsync(request, stoppingToken);
            }
            catch (OperationCanceledException) when (
                stoppingToken.IsCancellationRequested)
            {
                throw;
            }
            catch (Exception)
            {
                result = Failure(request, ConsumerFailureCode);
            }

            if (!Matches(request, result) ||
                !SecretReactionResultValidator.ValidateResult(result).IsValid)
            {
                result = Failure(request, InvalidResultCode);
            }

            outcomeSink.Report(result);
        }
    }

    /// <inheritdoc />
    public override void Dispose()
    {
        subscription?.Dispose();
        subscription = null;
        changes.Writer.TryComplete();
        base.Dispose();
    }

    private static bool Matches(
        SecretReactionRequest request,
        SecretReactionResult result) =>
        result.ReferenceIdentity == request.Signal.ReferenceIdentity &&
        result.Generation == request.Signal.Lifecycle.Generation &&
        result.Reaction == request.Reaction;

    private static SecretReactionResult Failure(
        SecretReactionRequest request,
        ProgramKitIdentifier code) =>
        new(
            request.Signal.ReferenceIdentity,
            request.Signal.Lifecycle.Generation,
            request.Reaction,
            SecretReactionStatus.Failed,
            code);
}
