// <auto-generated program-kit>
#nullable enable
using Orbyss.ProgramKit.SecretResolution.Contracts.Runtime;

namespace Orbyss.ProgramKit.SecretResolutionConsumerFixture.Hosting;

/// <summary>Consumer-owned implementation of the selected lifecycle reaction.</summary>
public interface IFixtureSecretSubscriptionReactionConsumer :
    ISecretReactionConsumer;
