using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Orbyss.ProgramKit.DotNet.Diagnostics;
using Orbyss.ProgramKit.DotNet.Documentation.Api;
using Orbyss.ProgramKit.DotNet.Operations.Security;
using Orbyss.ProgramKit.DotNet.Shells;
using Orbyss.ProgramKit.Workbench.Operations.Generation;

namespace Orbyss.ProgramKit.DotNet.Generation.FastEndpoints;

/// <summary>
/// Deterministic FastEndpoints syntax projection. ASP.NET Core middleware
/// remains the security and transport-failure owner.
/// </summary>
public sealed class DotNetFastEndpointsProjectionCompiler :
    IDotNetFastEndpointsProjectionCompiler
{
    /// <inheritdoc />
    public ImmutableArray<GeneratedOutput> Compile(
        DotNetHostDefinition host,
        OpenApiDocumentProjection? document)
    {
        ArgumentNullException.ThrowIfNull(host);
        if (host.FastEndpoints is null)
        {
            return [];
        }

        if (host.Kind != DotNetHostKind.Api || document is null)
        {
            throw DotNetKitException.Create(
                DotNetDiagnosticIds.InvalidFastEndpointsConfiguration,
                "FastEndpoints projection requires one accepted API document.",
                "/fastEndpoints");
        }

        var outputs = ImmutableArray.CreateBuilder<GeneratedOutput>();
        outputs.Add(new GeneratedOutput(
            "ProgramKitGenerated/Hosting/IProgramKitFastEndpointOperationDispatcher.cs",
            DotNetSourceText.Utf8(RenderDispatcher())));
        outputs.Add(new GeneratedOutput(
            "ProgramKitGenerated/Hosting/ProgramKitFastEndpointsFeature.cs",
            DotNetSourceText.Utf8(RenderFeature())));
        foreach (var operation in document.Operations
                     .OrderBy(static item => item.Path, StringComparer.Ordinal)
                     .ThenBy(static item => item.Method, StringComparer.Ordinal))
        {
            outputs.Add(new GeneratedOutput(
                string.Concat(
                    "ProgramKitGenerated/Hosting/",
                    EndpointName(operation),
                    ".cs"),
                DotNetSourceText.Utf8(RenderEndpoint(operation))));
        }

        outputs.Add(new GeneratedOutput(
            "ProgramKitGenerated/Hosting/fastendpoints-projection.json",
            RenderEvidence(host, document)));
        return outputs.ToImmutable();
    }

    private static string RenderDispatcher() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        /// <summary>
        /// Consumer-owned dispatch boundary for one exact projected operation.
        /// The implementation owns request, response, and operation behavior.
        /// </summary>
        public interface IProgramKitFastEndpointOperationDispatcher
        {
            /// <summary>Dispatches one exact operation through the current HTTP context.</summary>
            global::System.Threading.Tasks.ValueTask DispatchAsync(
                string operationRevision,
                global::Microsoft.AspNetCore.Http.HttpContext context,
                global::System.Threading.CancellationToken cancellationToken);
        }
        """;

    private static string RenderFeature() =>
        """
        // <auto-generated program-kit>
        #nullable enable

        namespace GeneratedHost.Hosting;

        /// <summary>
        /// Activates the exact FastEndpoints host adapter for one selected shell.
        /// </summary>
        [global::CShells.Features.ShellFeature(
            "ProgramKitFastEndpoints",
            DependsOn = ["FastEndpoints"])]
        public sealed class ProgramKitFastEndpointsFeature :
            global::CShells.FastEndpoints.Features.IFastEndpointsShellFeature
        {
            /// <inheritdoc />
            public void ConfigureServices(
                global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
            {
            }
        }
        """;

    private static string RenderEndpoint(OpenApiOperationProjection operation)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated program-kit>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace GeneratedHost.Hosting;");
        builder.AppendLine();
        builder.Append("internal sealed class ")
            .Append(EndpointName(operation))
            .AppendLine(
                " : global::FastEndpoints.EndpointWithoutRequest, global::FastEndpoints.IEndpoint");
        builder.AppendLine("{");
        builder.Append("    internal const string OperationRevision = ")
            .Append(DotNetSourceText.CSharpLiteral(Exact(operation.OperationRevision)))
            .AppendLine(";");
        builder.Append("    internal const string OperationId = ")
            .Append(DotNetSourceText.CSharpLiteral(operation.OperationId))
            .AppendLine(";");
        builder.Append("    internal const string Method = ")
            .Append(DotNetSourceText.CSharpLiteral(operation.Method))
            .AppendLine(";");
        builder.Append("    internal const string Path = ")
            .Append(DotNetSourceText.CSharpLiteral(operation.Path))
            .AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    public override void Configure()");
        builder.AppendLine("    {");
        builder.Append("        Verbs(")
            .Append(DotNetSourceText.CSharpLiteral(operation.Method))
            .AppendLine(");");
        builder.Append("        Routes(")
            .Append(DotNetSourceText.CSharpLiteral(operation.Path))
            .AppendLine(");");
        builder.AppendLine(
            "        // FastEndpoints security is neutralized; generated ASP.NET Core middleware owns the exact policy.");
        builder.AppendLine("        AllowAnonymous();");
        builder.AppendLine(
            "        // Exceptions must reach the generated ASP.NET Core exception-handler and Problem Details pipeline.");
        builder.AppendLine("        DontCatchExceptions();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine(
            "    public override async global::System.Threading.Tasks.Task HandleAsync(");
        builder.AppendLine(
            "        global::System.Threading.CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        builder.AppendLine(
            "        var dispatcher = Resolve<global::GeneratedHost.Hosting.IProgramKitFastEndpointOperationDispatcher>();");
        builder.AppendLine(
            "        await dispatcher.DispatchAsync(OperationRevision, HttpContext, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static ReadOnlyMemory<byte> RenderEvidence(
        DotNetHostDefinition host,
        OpenApiDocumentProjection document)
    {
        using MemoryStream stream = new();
        using (Utf8JsonWriter writer = new(
                   stream,
                   new JsonWriterOptions { Indented = true }))
        {
            writer.WriteStartObject();
            writer.WriteString(
                "profileRevision",
                Exact(host.FastEndpoints!.ProfileRevision));
            writer.WriteString(
                "shellAdapterPackage",
                string.Concat(
                    host.FastEndpoints.ShellAdapterPackage.PackageId,
                    "@",
                    host.FastEndpoints.ShellAdapterPackage.Version.Value,
                    "#",
                    host.FastEndpoints.ShellAdapterPackage.Sha256.Value));
            writer.WriteString(
                "fastEndpointsPackage",
                string.Concat(
                    host.FastEndpoints.FastEndpointsPackage.PackageId,
                    "@",
                    host.FastEndpoints.FastEndpointsPackage.Version.Value,
                    "#",
                    host.FastEndpoints.FastEndpointsPackage.Sha256.Value));
            writer.WriteString("openApiTitle", document.Title);
            writer.WriteString("openApiVersion", document.ApiVersion.Value);
            writer.WriteStartArray("operations");
            foreach (var operation in document.Operations
                         .OrderBy(static item => item.Path, StringComparer.Ordinal)
                         .ThenBy(static item => item.Method, StringComparer.Ordinal))
            {
                writer.WriteStartObject();
                writer.WriteString("operationRevision", Exact(operation.OperationRevision));
                writer.WriteString("operationId", operation.OperationId);
                writer.WriteString("method", operation.Method);
                writer.WriteString("path", operation.Path);
                WriteReferences(
                    writer,
                    "requestContractRevisions",
                    operation.InputSchemaRevisions);
                WriteReferences(
                    writer,
                    "resultContractRevisions",
                    operation.ResultSchemaRevisions);
                WriteReferences(
                    writer,
                    "diagnosticContractRevisions",
                    operation.DiagnosticSchemaRevisions);
                WriteSecurity(writer, operation.Security);
                writer.WriteStartArray("problemDetails");
                foreach (var problem in operation.ProblemDetailsResponses
                             .OrderBy(static item => item.StatusCode))
                {
                    writer.WriteStartObject();
                    writer.WriteNumber("statusCode", problem.StatusCode);
                    writer.WriteString(
                        "failureIdentity",
                        problem.FailureIdentity.Value);
                    writer.WriteString("type", problem.Type.AbsoluteUri);
                    writer.WriteString("title", problem.Title);
                    writer.WriteString(
                        "schemaRevision",
                        Exact(problem.ProblemSchemaRevision));
                    writer.WriteEndObject();
                }

                writer.WriteEndArray();
                writer.WriteEndObject();
            }

            writer.WriteEndArray();
            writer.WriteString(
                "securityOwner",
                "generated-aspnet-core-operation-authorization-middleware");
            writer.WriteString(
                "transportFailureOwner",
                "generated-aspnet-core-exception-handler-and-problem-details");
            writer.WriteBoolean("fastEndpointsSecurityNeutralized", true);
            writer.WriteBoolean("fastEndpointsExceptionCatchingDisabled", true);
            writer.WriteBoolean("parallelOpenApiGenerated", false);
            writer.WriteEndObject();
        }

        stream.WriteByte((byte)'\n');
        return stream.ToArray();
    }

    private static void WriteSecurity(
        Utf8JsonWriter writer,
        OpenApiOperationSecurityProjection? security)
    {
        writer.WriteStartObject("security");
        writer.WriteBoolean("anonymous", security?.Anonymous ?? true);
        if (security?.PolicyIdentity is { } policy)
        {
            writer.WriteString("policyIdentity", policy.Value);
        }
        else
        {
            writer.WriteNull("policyIdentity");
        }

        writer.WriteStartArray("schemeNames");
        var schemes = security is null
            ? ImmutableArray<string>.Empty
            : security.SchemeNames;
        foreach (var scheme in schemes.Order(StringComparer.Ordinal))
        {
            writer.WriteStringValue(scheme);
        }

        writer.WriteEndArray();
        writer.WriteEndObject();
    }

    private static void WriteReferences(
        Utf8JsonWriter writer,
        string propertyName,
        ImmutableArray<ArtifactReference> references)
    {
        writer.WriteStartArray(propertyName);
        foreach (var reference in references
                     .OrderBy(static item => item.Identity.Value, StringComparer.Ordinal)
                     .ThenBy(static item => item.Version.Value, StringComparer.Ordinal))
        {
            writer.WriteStringValue(Exact(reference));
        }

        writer.WriteEndArray();
    }

    private static string EndpointName(OpenApiOperationProjection operation)
    {
        var identity = string.Concat(
            operation.Method,
            "\n",
            operation.Path,
            "\n",
            Exact(operation.OperationRevision));
        var digest = Convert.ToHexStringLower(
            SHA256.HashData(Encoding.UTF8.GetBytes(identity)));
        return string.Concat("ProgramKitFastEndpoint", digest[..16]);
    }

    private static string Exact(ArtifactReference reference) =>
        string.Concat(
            reference.Identity.Value,
            "@",
            reference.Version.Value,
            "#",
            reference.Digest.Value);
}
