<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PackageId>Orbyss.ProgramKit.ConsoleContractFixtures</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CShells.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
