name: program-kit-application

services:
  application:
    image: program-kit-consumer:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CShells__Shells__default__Configuration__ProgramKit__Web__ClientSecret: local-program-kit-secret
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "5000:8080"
