using System.Collections.Immutable;

namespace Orbyss.ProgramKit.Artifacts;

/// <summary>A versioned boundary represented in the Program Kit version topology.</summary>
public enum VersionBoundaryKind
{
    /// <summary>A semantic contract.</summary>
    Contract,

    /// <summary>A serialized wire schema.</summary>
    Schema,

    /// <summary>A package revision.</summary>
    Package,

    /// <summary>An implementation revision.</summary>
    Implementation,

    /// <summary>A code or artifact generator.</summary>
    Generator,

    /// <summary>A generated input or output.</summary>
    GeneratedArtifact,

    /// <summary>A host composition or activation boundary.</summary>
    HostComposition,

    /// <summary>A serialization profile.</summary>
    SerializationProfile,

    /// <summary>A converter contribution.</summary>
    ConverterContribution,

    /// <summary>A canonicalization profile.</summary>
    CanonicalizationProfile,

    /// <summary>A configuration contract or selection.</summary>
    Configuration,

    /// <summary>A durable Program Kit artifact.</summary>
    Artifact,

    /// <summary>Persisted data outside the artifact envelope.</summary>
    PersistedData,

    /// <summary>A command-line surface.</summary>
    CommandLine,

    /// <summary>A task definition revision.</summary>
    TaskDefinition,

    /// <summary>A task schedule revision.</summary>
    TaskSchedule,

    /// <summary>An explicitly bounded external consumer.</summary>
    ExternalConsumer,
}

/// <summary>The semantic relationship represented by a version-map edge.</summary>
public enum VersionDependencyKind
{
    /// <summary>The source implements the target contract.</summary>
    Implements,

    /// <summary>The source reads the target representation.</summary>
    Reads,

    /// <summary>The source writes the target representation.</summary>
    Writes,

    /// <summary>The source validates the target.</summary>
    Validates,

    /// <summary>The source uses the target contract.</summary>
    UsesContract,

    /// <summary>The source is the wire schema of the target.</summary>
    WireSchemaOf,

    /// <summary>The source serializes with the target profile.</summary>
    SerializesWith,

    /// <summary>The source contributes a converter to the target profile.</summary>
    ContributesConverter,

    /// <summary>The source canonicalizes with the target profile.</summary>
    CanonicalizesWith,

    /// <summary>The source publicly exposes the target.</summary>
    PubliclyExposes,

    /// <summary>The source package depends on the target package.</summary>
    PackageDependsOn,

    /// <summary>The source is configured by the target.</summary>
    ConfiguredBy,

    /// <summary>The source is generated by the target.</summary>
    GeneratedBy,

    /// <summary>The source projects the target.</summary>
    Projects,

    /// <summary>The source composes the target.</summary>
    Composes,

    /// <summary>The source handles the target task definition.</summary>
    HandlesTask,

    /// <summary>The source schedules the target task definition.</summary>
    Schedules,

    /// <summary>The source migrates the target.</summary>
    Migrates,

    /// <summary>The source verifies the target.</summary>
    Verifies,
}

/// <summary>Whether a version dependency crosses a public consumer boundary.</summary>
public enum DependencyExposure
{
    /// <summary>The dependency is an implementation detail.</summary>
    Private,

    /// <summary>The dependency is exposed to consumers.</summary>
    Public,
}

/// <summary>A required exact resolution constrained by an accepted version range.</summary>
/// <param name="Identity">The required semantic identity.</param>
/// <param name="AcceptedRange">The accepted range.</param>
/// <param name="Resolution">The exact resolved revision.</param>
/// <param name="Exposure">Whether the requirement is publicly exposed.</param>
/// <param name="Dimensions">Compatibility dimensions relevant to the requirement.</param>
/// <param name="EvidenceReferences">Exact evidence supporting the requirement.</param>
public sealed record VersionRequirement(
    ProgramKitIdentifier Identity,
    SemanticVersionRange AcceptedRange,
    ArtifactReference Resolution,
    DependencyExposure Exposure,
    ImmutableArray<CompatibilityDimension> Dimensions,
    ImmutableArray<ArtifactReference> EvidenceReferences);

/// <summary>Describes one independently versioned and consumed component boundary.</summary>
/// <param name="Identity">The stable component identity.</param>
/// <param name="Kind">The boundary kind.</param>
/// <param name="OwnerId">The owning semantic identity.</param>
/// <param name="Version">The component's independent version.</param>
/// <param name="Digest">The exact component digest.</param>
/// <param name="ProvidedContracts">Exact contracts provided by the component.</param>
/// <param name="RequiredContracts">Range-constrained, exactly resolved requirements.</param>
/// <param name="CompatibilityClaims">Independent compatibility claims.</param>
/// <param name="MigrationReferences">Migration definitions available for this revision.</param>
public sealed record VersionedComponentManifest(
    ProgramKitIdentifier Identity,
    VersionBoundaryKind Kind,
    ProgramKitIdentifier OwnerId,
    SemanticVersion Version,
    Sha256Digest Digest,
    ImmutableArray<ArtifactReference> ProvidedContracts,
    ImmutableArray<VersionRequirement> RequiredContracts,
    ImmutableArray<CompatibilityClaim> CompatibilityClaims,
    ImmutableArray<ArtifactReference> MigrationReferences)
{
    /// <summary>Gets the exact component revision represented by this manifest.</summary>
    public ArtifactReference Revision => new(Identity, Version, Digest);
}

/// <summary>A revision node in an immutable version-map snapshot.</summary>
/// <param name="Revision">The exact node revision.</param>
/// <param name="Kind">The represented boundary kind.</param>
/// <param name="OwnerId">The owner responsible for migration decisions.</param>
/// <param name="EvidenceReferences">Exact evidence describing the revision.</param>
public sealed record VersionRevisionNode(
    ArtifactReference Revision,
    VersionBoundaryKind Kind,
    ProgramKitIdentifier OwnerId,
    ImmutableArray<ArtifactReference> EvidenceReferences);

/// <summary>A typed, exactly resolved dependency edge.</summary>
/// <param name="Id">The stable edge identity.</param>
/// <param name="Source">The exact dependent revision.</param>
/// <param name="TargetIdentity">The required semantic identity.</param>
/// <param name="Kind">The semantic dependency kind.</param>
/// <param name="AcceptedRange">The accepted target range.</param>
/// <param name="Resolution">The exact target resolution.</param>
/// <param name="Exposure">Whether the edge is publicly exposed.</param>
/// <param name="CompatibilityDimensions">Dimensions relevant to the dependency.</param>
/// <param name="EvidenceReferences">Exact evidence supporting the edge.</param>
public sealed record VersionDependencyEdge(
    ProgramKitIdentifier Id,
    ArtifactReference Source,
    ProgramKitIdentifier TargetIdentity,
    VersionDependencyKind Kind,
    SemanticVersionRange AcceptedRange,
    ArtifactReference Resolution,
    DependencyExposure Exposure,
    ImmutableArray<CompatibilityDimension> CompatibilityDimensions,
    ImmutableArray<ArtifactReference> EvidenceReferences);

/// <summary>An immutable staged snapshot of versioned nodes and typed dependencies.</summary>
/// <param name="Nodes">All exact revision nodes.</param>
/// <param name="Edges">All typed dependency edges.</param>
public sealed record VersionMapDocument(
    ImmutableArray<VersionRevisionNode> Nodes,
    ImmutableArray<VersionDependencyEdge> Edges);

/// <summary>Binds one observed revision to one human-selected target revision.</summary>
/// <param name="Identity">The selected semantic identity.</param>
/// <param name="Observed">The exact observed revision.</param>
/// <param name="Target">The exact target revision.</param>
/// <param name="OwnerId">The owner responsible for the selection.</param>
public sealed record VersionSelection(
    ProgramKitIdentifier Identity,
    ArtifactReference Observed,
    ArtifactReference Target,
    ProgramKitIdentifier OwnerId);

/// <summary>An immutable set of observed and human-selected exact revisions.</summary>
/// <param name="InputVersionMap">The immutable version map used for selection.</param>
/// <param name="Selections">Selections keyed by stable identity.</param>
public sealed record VersionSelectionDocument(
    ArtifactReference InputVersionMap,
    ImmutableArray<VersionSelection> Selections);
