ARG ORBYSS_FOUNDATION_HOST_IMAGE
FROM ${ORBYSS_FOUNDATION_HOST_IMAGE}
COPY artifacts/runnable-host/packages/ /app/packages/
COPY artifacts/runnable-host/hostsettings.json /app/hostsettings.json
COPY artifacts/runnable-host/shells.json /app/shells.json
COPY artifacts/runnable-host/.program-kit/web-profile.shells.json /app/.program-kit/web-profile.shells.json
