ARG PROGRAMKIT_HOST_IMAGE
FROM ${PROGRAMKIT_HOST_IMAGE}
COPY artifacts/runnable-host/packages/ /app/packages/
COPY artifacts/runnable-host/hostsettings.json /app/hostsettings.json
COPY artifacts/runnable-host/shells.json /app/shells.json
