<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GeneratedPublicBrowser</RootNamespace>
    <AssemblyName>Orbyss.ProgramKit.PublicBrowserConsumerFixture</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
  </ItemGroup>
</Project>
