using Orbyss.ProgramKit.DotNet.Packages;

namespace Orbyss.ProgramKit.DotNet.Configuration;

/// <summary>Immutable explicitly assembled configuration-provider catalog.</summary>
public sealed class DotNetConfigurationProviderCatalog :
    IDotNetConfigurationProviderCatalog
{
    private const string ProviderVersion = "10.0.10";
    private const string GeneratorDigest =
        "sha256:695848c25e2521ce8b0e8b1010041964e8014bc6a10c8e62f05b357bc2f57160";
    private static readonly ImmutableArray<string> FileWatcherLimitations =
    [
        "filesystem notifications can be delayed, coalesced, or absent on container bind mounts and network shares",
        "polling fallback is not generated by provider ABI 1.0.0",
    ];

    /// <summary>Gets the exact reviewed .NET 10 built-in descriptors.</summary>
    internal static ImmutableArray<DotNetConfigurationProviderDescriptor>
        BuiltInDescriptors
    { get; } =
    [
        Descriptor(
                "json-file",
                DotNetConfigurationProviderKind.JsonFile,
                "Microsoft.Extensions.Configuration.Json",
                "9f03c48b4704b643a6f1780f421fc156e3e7f2a27c1e837c674898865c13b618",
                "c60fb6d50465f46c918b96b104eb54a4a1c6fcc6196c3063b99e44b490a8065a",
                [DotNetConfigurationReloadCapability.None, DotNetConfigurationReloadCapability.ChangeToken],
                DotNetConfigurationReloadMechanism.FileProviderChangeToken,
                false,
                [DotNetConfigurationSecretClassification.PublicOnly, DotNetConfigurationSecretClassification.ReferencesOnly],
                FileWatcherLimitations),
            Descriptor(
                "environment-variables",
                DotNetConfigurationProviderKind.EnvironmentVariables,
                "Microsoft.Extensions.Configuration.EnvironmentVariables",
                "15283ddb052f27e64ebf58cf4569d70e3cc6bcd9afa20fb59ffdd909e674a7d6",
                "fb018ae1bd456fc003bfb475ee4b8f356fcd57c943155ac5742a387cbd7129a2",
                [DotNetConfigurationReloadCapability.None],
                DotNetConfigurationReloadMechanism.None,
                false,
                [
                    DotNetConfigurationSecretClassification.PublicOnly,
                    DotNetConfigurationSecretClassification.ReferencesOnly,
                    DotNetConfigurationSecretClassification.ProviderOwned,
                ],
                ["process environment is captured without an automatic change token"]),
            Descriptor(
                "command-line",
                DotNetConfigurationProviderKind.CommandLine,
                "Microsoft.Extensions.Configuration.CommandLine",
                "c490b09b6d40594a1b7218a075ce8720bb9d8178240fc08e7f67d59baeef2476",
                "63a8865831d12352dd577f149174b0da01b6b69bf968bd4bbaf3c64023387605",
                [DotNetConfigurationReloadCapability.None],
                DotNetConfigurationReloadMechanism.None,
                false,
                [DotNetConfigurationSecretClassification.PublicOnly, DotNetConfigurationSecretClassification.ReferencesOnly],
                ["command-line values are startup-fixed and can be visible to process inspection"]),
            Descriptor(
                "in-memory",
                DotNetConfigurationProviderKind.InMemory,
                "Microsoft.Extensions.Configuration",
                "b45684c6e7cd18f15d513b30aa4891572452f794395c6e562c212847aa1a29f1",
                "e8b8e70703c3280a282ebaa5a8d0222f0558c447aec9e07930190a819ab0bcc6",
                [DotNetConfigurationReloadCapability.None],
                DotNetConfigurationReloadMechanism.None,
                false,
                [DotNetConfigurationSecretClassification.PublicOnly],
                ["generated initial values are startup-fixed and must be public"]),
            Descriptor(
                "user-secrets",
                DotNetConfigurationProviderKind.UserSecrets,
                "Microsoft.Extensions.Configuration.UserSecrets",
                "19a4af6fcf15765c3b2d993ad3e3c89701475464195788cddda4520f11917808",
                "1bbb30ec22dca4e4c731850a40424276e86a92805f953bb72a519bbd9505b4da",
                [DotNetConfigurationReloadCapability.None, DotNetConfigurationReloadCapability.ChangeToken],
                DotNetConfigurationReloadMechanism.FileProviderChangeToken,
                true,
                [DotNetConfigurationSecretClassification.ProviderOwned],
                FileWatcherLimitations.Add("user secrets are development-only and are not a production secret store")),
            Descriptor(
                "key-per-file",
                DotNetConfigurationProviderKind.KeyPerFile,
                "Microsoft.Extensions.Configuration.KeyPerFile",
                "484feb243cb5c3611eea2a691357876f9ee09b7592e77e6c5ff3a913a450a132",
                "52da9a53409730c00fbdd9796f796e80b152004429111d83228a73df5bb58e53",
                [DotNetConfigurationReloadCapability.None, DotNetConfigurationReloadCapability.ChangeToken],
                DotNetConfigurationReloadMechanism.FileProviderChangeToken,
                false,
                [DotNetConfigurationSecretClassification.ProviderOwned],
                FileWatcherLimitations),
            Descriptor(
                "chained-configuration",
                DotNetConfigurationProviderKind.ChainedConfiguration,
                "Microsoft.Extensions.Configuration",
                "b45684c6e7cd18f15d513b30aa4891572452f794395c6e562c212847aa1a29f1",
                "e8b8e70703c3280a282ebaa5a8d0222f0558c447aec9e07930190a819ab0bcc6",
                [DotNetConfigurationReloadCapability.None],
                DotNetConfigurationReloadMechanism.None,
                false,
                [DotNetConfigurationSecretClassification.PublicOnly],
                ["ABI 1.0.0 chains an explicitly generated secret-free, startup-fixed configuration root"]),
    ];

    /// <summary>Initializes a catalog from explicit descriptors.</summary>
    public DotNetConfigurationProviderCatalog(
        IEnumerable<DotNetConfigurationProviderDescriptor> providers)
    {
        ArgumentNullException.ThrowIfNull(providers);
        Providers = providers.ToImmutableArray();
        if (Providers.IsDefaultOrEmpty ||
            Providers.Any(static descriptor => descriptor is null) ||
            Providers.Select(static descriptor => ExactKey(descriptor.ProviderRevision))
                .Distinct(StringComparer.Ordinal)
                .Count() != Providers.Length)
        {
            throw new ArgumentException(
                "Provider descriptors must be non-empty and exact-revision unique.",
                nameof(providers));
        }
    }

    /// <inheritdoc />
    public ImmutableArray<DotNetConfigurationProviderDescriptor> Providers { get; }

    /// <inheritdoc />
    public DotNetConfigurationProviderDescriptor? Resolve(
        ArtifactReference providerRevision)
    {
        ArgumentNullException.ThrowIfNull(providerRevision);
        var key = ExactKey(providerRevision);
        return Providers.FirstOrDefault(descriptor =>
            string.Equals(
                ExactKey(descriptor.ProviderRevision),
                key,
                StringComparison.Ordinal));
    }

    private static DotNetConfigurationProviderDescriptor Descriptor(
        string name,
        DotNetConfigurationProviderKind kind,
        string packageId,
        string packageDigest,
        string assemblyDigest,
        ImmutableArray<DotNetConfigurationReloadCapability> reload,
        DotNetConfigurationReloadMechanism mechanism,
        bool developmentOnly,
        ImmutableArray<DotNetConfigurationSecretClassification> classifications,
        ImmutableArray<string> limitations) =>
        new(
            new ArtifactReference(
                new ProgramKitIdentifier(
                    string.Concat("pkid:provider:program-kit:dotnet-configuration-", name)),
                new SemanticVersion(ProviderVersion),
                new Sha256Digest(string.Concat("sha256:", assemblyDigest))),
            kind,
            new DotNetPackageReference(
                packageId,
                new SemanticVersion(ProviderVersion),
                new Sha256Digest(string.Concat("sha256:", packageDigest))),
            new ArtifactReference(
                new ProgramKitIdentifier(
                    "pkid:generator:program-kit:dotnet-configuration-provider"),
                new SemanticVersion("1.0.0"),
                new Sha256Digest(GeneratorDigest)),
            reload,
            mechanism,
            developmentOnly,
            classifications,
            limitations);

    private static string ExactKey(ArtifactReference reference) =>
        string.Concat(
            reference.Identity.Value,
            "@",
            reference.Version.Value,
            "#",
            reference.Digest.Value);
}
