// <auto-generated program-kit>
#nullable enable

using GeneratedHost.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;

namespace GeneratedHost.Composition;

internal static class SecurityRegistrationProbe
{
    internal static void Register(
        WebApplicationBuilder builder,
        bool assertionAuthentication)
    {
        var authentication = builder.Services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = "ProgramKit.Jwt";
            options.DefaultChallengeScheme = "ProgramKit.Jwt";
            options.DefaultForbidScheme = "ProgramKit.Jwt";
            options.DefaultSignInScheme = "ProgramKit.Cookie";
            options.DefaultSignOutScheme = "ProgramKit.Oidc";
        });
        authentication.AddCookie("ProgramKit.Cookie", options =>
        {
            options.Cookie.Name = "__Host-program-kit-session";
            options.Cookie.HttpOnly = true;
            options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
            options.Cookie.SameSite = SameSiteMode.Lax;
            options.Cookie.IsEssential = false;
            options.ExpireTimeSpan = TimeSpan.FromMinutes(60);
            options.SlidingExpiration = false;
        });
        authentication.AddOpenIdConnect("ProgramKit.Oidc", options =>
        {
            options.SignInScheme = "ProgramKit.Cookie";
            options.Authority = "https://identity.example.test/";
            options.MetadataAddress =
                "https://identity.example.test/.well-known/openid-configuration";
            options.ClientId = "fixture-client";
            options.ResponseType =
                Microsoft.IdentityModel.Protocols.OpenIdConnect
                    .OpenIdConnectResponseType.Code;
            options.ResponseMode =
                Microsoft.IdentityModel.Protocols.OpenIdConnect
                    .OpenIdConnectResponseMode.FormPost;
            options.CallbackPath = "/signin-oidc";
            options.SignedOutCallbackPath = "/signout-callback-oidc";
            options.RemoteSignOutPath = "/signout-oidc";
            options.RequireHttpsMetadata = true;
            options.UsePkce = true;
            options.MapInboundClaims = false;
            options.SaveTokens = false;
            options.GetClaimsFromUserInfoEndpoint = false;
            options.DisableTelemetry = true;
            options.RemoteAuthenticationTimeout = TimeSpan.FromMinutes(5);
            options.ProtocolValidator.RequireNonce = true;
            options.ProtocolValidator.RequireStateValidation = true;
            options.PushedAuthorizationBehavior =
                PushedAuthorizationBehavior.UseIfAvailable;
            options.Scope.Clear();
            options.Scope.Add("openid");
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidateAudience = true,
                ValidateIssuerSigningKey = true,
                ValidateLifetime = true,
                ValidAudience = "fixture-client",
                ValidAlgorithms = ["RS256", "PS256", "ES256"],
            };
            options.CorrelationCookie.HttpOnly = true;
            options.CorrelationCookie.SecurePolicy =
                CookieSecurePolicy.Always;
            options.CorrelationCookie.SameSite = SameSiteMode.None;
            options.CorrelationCookie.IsEssential = false;
            options.NonceCookie.HttpOnly = true;
            options.NonceCookie.SecurePolicy = CookieSecurePolicy.Always;
            options.NonceCookie.SameSite = SameSiteMode.None;
            options.NonceCookie.IsEssential = false;
            if (assertionAuthentication)
            {
                options.Events.OnAuthorizationCodeReceived = async context =>
                {
                    var provider = context.HttpContext.RequestServices
                        .GetRequiredService<
                            IProgramKitOidcClientAssertionProvider>();
                    var assertion = await provider.CreateAsync(
                        "pkid:secret-reference:fixture:oidc-client",
                        context.HttpContext.RequestAborted);
                    if (string.IsNullOrEmpty(assertion.Value) ||
                        assertion.ExpiresAt <= DateTimeOffset.UtcNow)
                    {
                        throw new InvalidOperationException(
                            "The OIDC client assertion is empty or expired.");
                    }

                    var tokenEndpointRequest =
                        context.TokenEndpointRequest ??
                        throw new InvalidOperationException(
                            "The OIDC token endpoint request is unavailable.");
                    tokenEndpointRequest.ClientAssertion =
                        assertion.Value;
                    tokenEndpointRequest.ClientAssertionType =
                        "urn:ietf:params:oauth:client-assertion-type:jwt-bearer";
                };
            }
            else
            {
                options.ClientSecret =
                    builder.Configuration[
                        "Authentication:Oidc:ClientSecret"] ??
                    "fixture-build-only-value";
            }
        });
        authentication.AddJwtBearer("ProgramKit.Jwt", options =>
        {
            options.Authority = "https://identity.example.test/";
            options.MetadataAddress =
                "https://identity.example.test/.well-known/openid-configuration";
            options.Audience = "fixture-api";
            options.RequireHttpsMetadata = true;
            options.MapInboundClaims = false;
            options.SaveToken = false;
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                RequireSignedTokens = true,
                ValidateIssuer = true,
                ValidIssuer = "https://identity.example.test/",
                ValidateAudience = true,
                ValidAudience = "fixture-api",
                ValidateLifetime = true,
                RequireExpirationTime = true,
                ClockSkew = TimeSpan.FromSeconds(60),
                ValidAlgorithms = ["RS256", "PS256", "ES256"],
                ValidTypes = ["at+jwt"],
            };
        });
        builder.Services.AddAuthorizationBuilder()
            .AddPolicy(
                "ProgramKit.AuthenticatedTransport",
                policy =>
                {
                    policy.AddAuthenticationSchemes("ProgramKit.Jwt");
                    policy.RequireAuthenticatedUser();
                });
    }
}
